# -*- coding: utf-8 -*-
"""
100个编程领域知识体系配置
每个领域定义模块结构，确保难度递进和领域特异性
"""

# 100个领域配置：name, count, category, modules(模块名列表)
# 模块按难度递进排列：基础→核心→高级→实战
DOMAINS_CONFIG = [
    # ===== 系统与底层（12个）=====
    {"name": "Linux内核", "count": 200, "category": "系统底层",
     "modules": ["内核基础与启动", "进程管理与调度", "内存管理", "中断与时间", "同步机制",
                 "文件系统VFS", "网络协议栈", "设备驱动模型", "系统调用与IPC", "性能调优与追踪"]},
    {"name": "Linux系统编程", "count": 120, "category": "系统底层",
     "modules": ["文件IO操作", "进程控制", "信号处理", "进程间通信", "线程编程",
                 "网络套接字", "IO多路复用", "内存映射", "终端编程", "守护进程与服务"]},
    {"name": "操作系统原理", "count": 120, "category": "系统底层",
     "modules": ["操作系统概述", "进程与线程", "进程调度", "进程同步", "死锁处理",
                 "内存管理", "虚拟内存", "文件系统", "IO系统", "磁盘调度", "安全与保护"]},
    {"name": "计算机网络", "count": 120, "category": "系统底层",
     "modules": ["网络体系结构", "物理层与数据链路层", "网络层IP", "传输层TCP/UDP", "应用层协议",
                 "网络安全", "网络编程", "网络性能", "无线网络", "网络管理"]},
    {"name": "编译原理", "count": 100, "category": "系统底层",
     "modules": ["编译概述", "词法分析", "语法分析", "语义分析", "中间代码生成",
                 "代码优化", "目标代码生成", "运行时环境", "链接与加载", "JIT与解释器"]},
    {"name": "计算机组成原理", "count": 100, "category": "系统底层",
     "modules": ["计算机系统概述", "数据的表示与运算", "存储系统", "指令系统", "中央处理器",
                 "总线系统", "IO系统", "流水线技术", "多处理器", "性能评估"]},
    {"name": "汇编语言", "count": 80, "category": "系统底层",
     "modules": ["汇编基础", "数据传送与运算", "流程控制", "子程序与栈", "寻址方式",
                 "中断与系统调用", "宏与伪指令", "x86_64汇编", "ARM汇编", "汇编优化"]},
    {"name": "嵌入式系统", "count": 100, "category": "系统底层",
     "modules": ["嵌入式概述", "嵌入式处理器", "嵌入式操作系统", "设备驱动开发", "外设接口",
                 "实时系统", "嵌入式网络", "低功耗设计", "嵌入式调试", "嵌入式安全"]},
    {"name": "驱动开发", "count": 100, "category": "系统底层",
     "modules": ["驱动模型基础", "字符设备驱动", "块设备驱动", "网络设备驱动", "平台设备驱动",
                 "PCI设备驱动", "USB设备驱动", "输入子系统", "中断与定时", "驱动调试"]},
    {"name": "虚拟化技术", "count": 80, "category": "系统底层",
     "modules": ["虚拟化概述", "CPU虚拟化", "内存虚拟化", "IO虚拟化", "全虚拟化与半虚拟化",
                 "容器虚拟化", "KVM详解", "Xen架构", "性能优化", "虚拟化安全"]},
    {"name": "容器技术", "count": 100, "category": "系统底层",
     "modules": ["容器概述", "Namespace", "Cgroups", "UnionFS", "Docker基础",
                 "Docker镜像", "Docker网络", "Docker存储", "容器安全", "容器编排基础"]},
    {"name": "实时系统", "count": 80, "category": "系统底层",
     "modules": ["实时系统概述", "实时调度", "实时内核", "实时通信", "实时IO",
                 "确定性保证", "容错设计", "性能分析", "实时Linux", "嵌入式实时"]},

    # ===== 编程语言（14个）=====
    {"name": "C语言", "count": 120, "category": "编程语言",
     "modules": ["C语言基础", "数据类型", "运算符与表达式", "流程控制", "函数",
                 "数组与指针", "结构体与联合", "内存管理", "文件IO", "预处理",
                 "高级特性", "C标准库", "C语言最佳实践"]},
    {"name": "C++", "count": 200, "category": "编程语言",
     "modules": ["C++基础", "类与对象", "继承与多态", "运算符重载", "模板",
                 "STL容器", "STL算法", "智能指针", "异常处理", "RTTI与类型转换",
                 "Lambda与函数对象", "并发编程", "C++11/14/17/20新特性", "设计模式", "性能优化"]},
    {"name": "Python核心", "count": 200, "category": "编程语言",
     "modules": ["Python基础", "数据类型", "流程控制", "函数", "模块与包",
                 "面向对象", "异常处理", "文件IO", "迭代器与生成器", "装饰器",
                 "上下文管理器", "正则表达式", "标准库", "虚拟环境与包管理", "Python最佳实践"]},
    {"name": "Python高级", "count": 120, "category": "编程语言",
     "modules": ["Python内存管理", "GIL与并发", "多线程与多进程", "asyncio异步", "元编程",
                 "描述符与属性", "类型注解", "C扩展", "性能分析与优化", "设计模式",
                 "函数式编程", "数据处理", "Web开发基础", "测试与调试", "Python高级技巧"]},
    {"name": "JavaScript核心", "count": 200, "category": "编程语言",
     "modules": ["JS基础语法", "数据类型", "运算符", "流程控制", "函数",
                 "对象与原型", "数组", "闭包与作用域", "this绑定", "ES6+新特性",
                 "异步编程", "Promise与async/await", "模块化", "DOM操作", "事件处理",
                 "错误处理", "JS最佳实践"]},
    {"name": "TypeScript", "count": 100, "category": "编程语言",
     "modules": ["TypeScript基础", "类型系统", "接口", "类", "泛型",
                 "枚举", "类型守卫", "装饰器", "模块", "命名空间",
                 "tsconfig配置", "与JavaScript互操作", "类型体操", "工程化", "最佳实践"]},
    {"name": "Java核心", "count": 150, "category": "编程语言",
     "modules": ["Java基础", "面向对象", "集合框架", "异常处理", "泛型",
                 "注解", "反射", "IO与NIO", "多线程基础", "JVM内存模型",
                 "垃圾回收", "类加载机制", "Java8新特性", "模块化系统", "Java最佳实践"]},
    {"name": "Java并发", "count": 120, "category": "编程语言",
     "modules": ["线程基础", "线程池", "synchronized", "Lock体系", "原子类",
                 "并发容器", "AQS原理", "Condition", "CountDownLatch", "CyclicBarrier",
                 "Semaphore", "Future与CompletableFuture", "ForkJoinPool", "并发设计模式", "并发性能调优"]},
    {"name": "Go语言", "count": 120, "category": "编程语言",
     "modules": ["Go基础", "数据类型", "流程控制", "函数", "结构体与方法",
                 "接口", "goroutine", "channel", "并发模式", "错误处理",
                 "包管理", "测试", "反射", "泛型", "性能优化", "Go最佳实践"]},
    {"name": "Rust语言", "count": 100, "category": "编程语言",
     "modules": ["Rust基础", "所有权", "借用与引用", "生命周期", "结构体与枚举",
                 "模式匹配", "trait", "泛型", "错误处理", "集合",
                 "模块与包", "闭包与迭代器", "智能指针", "并发安全", "异步编程", "Rust最佳实践"]},
    {"name": "PHP", "count": 80, "category": "编程语言",
     "modules": ["PHP基础", "数据类型", "流程控制", "函数", "数组",
                 "面向对象", "异常处理", "文件操作", "数据库操作", "PHP7+新特性",
                 "Composer", "Laravel基础", "性能优化", "安全编程", "PHP最佳实践"]},
    {"name": "C#", "count": 100, "category": "编程语言",
     "modules": ["C#基础", "类型系统", "面向对象", "泛型", "委托与事件",
                 "LINQ", "异步编程", "属性与反射", "异常处理", "集合",
                 ".NET平台", "ASP.NET基础", "依赖注入", "性能优化", "C#最佳实践"]},
    {"name": "函数式编程", "count": 80, "category": "编程语言",
     "modules": ["函数式编程概述", "纯函数", "不可变性", "高阶函数", "闭包",
                 "柯里化", "组合", "函子", "Monad", "模式匹配",
                 "代数数据类型", "惰性求值", "递归", "函数式并发", "函数式设计模式"]},
    {"name": "面向对象编程", "count": 80, "category": "编程语言",
     "modules": ["面向对象概述", "类与对象", "封装", "继承", "多态",
                 "抽象类与接口", "组合优于继承", "SOLID原则", "设计模式", "UML建模",
                 "面向对象分析", "面向对象设计", "重构", "领域建模", "面向对象最佳实践"]},

    # ===== 前端开发（10个）=====
    {"name": "HTML与CSS", "count": 120, "category": "前端开发",
     "modules": ["HTML基础", "HTML语义化", "表单", "多媒体", "Canvas",
                 "CSS基础", "选择器", "盒模型", "布局", "Flexbox",
                 "Grid", "响应式设计", "动画与过渡", "CSS预处理器", "性能优化", "最佳实践"]},
    {"name": "React", "count": 200, "category": "前端开发",
     "modules": ["React基础", "JSX", "组件", "Props与State", "事件处理",
                 "生命周期", "Hooks", "useState", "useEffect", "自定义Hook",
                 "Context", "性能优化", "路由", "状态管理", "服务端渲染",
                 "React测试", "React最佳实践"]},
    {"name": "Vue", "count": 120, "category": "前端开发",
     "modules": ["Vue基础", "模板语法", "计算属性", "侦听器", "Class与Style",
                 "条件渲染", "列表渲染", "事件处理", "表单输入", "组件基础",
                 "组件通信", "插槽", "生命周期", "Vue Router", "Pinia状态管理",
                 "组合式API", "Vue3新特性", "Vue最佳实践"]},
    {"name": "Node.js", "count": 120, "category": "前端开发",
     "modules": ["Node.js基础", "模块系统", "事件循环", "Buffer", "Stream",
                 "文件系统", "HTTP服务", "Express框架", "Koa框架", "中间件",
                 "数据库操作", "认证授权", "进程管理", "异步编程", "性能优化",
                 "调试与测试", "Node.js最佳实践"]},
    {"name": "前端工程化", "count": 100, "category": "前端开发",
     "modules": ["工程化概述", "包管理", "构建工具", "Webpack", "Vite",
                 "Rollup", "代码规范", "ESLint", "Prettier", "Babel",
                 "TypeScript工程", "单元测试", "E2E测试", "CI/CD", "性能监控",
                 "微前端", "前端最佳实践"]},
    {"name": "浏览器原理", "count": 100, "category": "前端开发",
     "modules": ["浏览器架构", "渲染流程", "HTML解析", "CSS解析", "布局",
                 "绘制", "合成", "事件循环", "垃圾回收", "V8引擎",
                 "网络栈", "安全机制", "同源策略", "存储", "PWA",
                 "浏览器调试", "浏览器性能优化"]},
    {"name": "Web性能优化", "count": 100, "category": "前端开发",
     "modules": ["性能指标", "加载性能", "渲染性能", "网络优化", "资源优化",
                 "图片优化", "代码分割", "懒加载", "预加载", "缓存策略",
                 "CDN", "HTTP/2与HTTP/3", "运行时优化", "性能监控", "性能预算",
                 "Lighthouse", "性能优化最佳实践"]},
    {"name": "PWA", "count": 60, "category": "前端开发",
     "modules": ["PWA概述", "Service Worker", "Web App Manifest", "离线缓存", "推送通知",
                 "后台同步", "安装体验", "性能要求", "安全要求", "PWA最佳实践"]},
    {"name": "Angular", "count": 80, "category": "前端开发",
     "modules": ["Angular基础", "组件", "模板", "数据绑定", "指令",
                 "管道", "服务与依赖注入", "路由", "表单", "HTTP客户端",
                 "RxJS", "状态管理", "测试", "性能优化", "Angular最佳实践"]},
    {"name": "小程序开发", "count": 80, "category": "前端开发",
     "modules": ["小程序概述", "WXML", "WXSS", "JS逻辑", "组件",
                 "页面路由", "API", "云开发", "性能优化", "微信小程序",
                 "支付宝小程序", "跨端框架", "小程序最佳实践"]},

    # ===== 后端开发（12个）=====
    {"name": "后端架构", "count": 120, "category": "后端开发",
     "modules": ["架构概述", "单体架构", "分层架构", "微服务架构", "SOA",
                 "事件驱动", "CQRS", "DDD", "API设计", "数据架构",
                 "缓存架构", "消息架构", "高可用", "高并发", "可扩展",
                 "安全架构", "后端架构最佳实践"]},
    {"name": "RESTful API", "count": 100, "category": "后端开发",
     "modules": ["REST概述", "资源建模", "HTTP方法", "状态码", "URI设计",
                 "请求与响应", "版本控制", "认证授权", "分页", "过滤排序",
                 "错误处理", "API文档", "API测试", "性能优化", "安全",
                 "HATEOAS", "REST最佳实践"]},
    {"name": "微服务架构", "count": 120, "category": "后端开发",
     "modules": ["微服务概述", "服务拆分", "服务通信", "服务发现", "API网关",
                 "配置中心", "服务熔断", "服务降级", "限流", "分布式事务",
                 "链路追踪", "日志聚合", "监控告警", "容器化部署", "服务网格",
                 "微服务测试", "微服务最佳实践"]},
    {"name": "Spring Boot", "count": 120, "category": "后端开发",
     "modules": ["Spring Boot基础", "自动配置", "Starter", "Web开发", "数据访问",
                 "安全", "缓存", "消息", "任务调度", "监控",
                 "测试", "配置管理", "日志", "性能优化", "部署",
                 "Spring Cloud", "Spring Boot最佳实践"]},
    {"name": "认证授权", "count": 80, "category": "后端开发",
     "modules": ["认证概述", "Session", "Cookie", "JWT", "OAuth2",
                 "OpenID Connect", "SSO单点登录", "RBAC", "ABAC", "多因素认证",
                 "密码安全", "Token管理", "API安全", "权限设计", "认证授权最佳实践"]},
    {"name": "API设计", "count": 80, "category": "后端开发",
     "modules": ["API设计原则", "REST设计", "GraphQL设计", "RPC设计", "API版本",
                 "API文档", "API测试", "API网关", "API安全", "API性能",
                 "API生命周期", "API治理", "API市场", "API设计模式", "API最佳实践"]},
    {"name": "Serverless", "count": 80, "category": "后端开发",
     "modules": ["Serverless概述", "函数计算", "事件驱动", "AWS Lambda", "阿里云函数计算",
                 "API网关", "无服务器架构", "冷启动", "状态管理", "调试",
                 "部署", "成本优化", "安全", "性能", "Serverless最佳实践"]},
    {"name": "GraphQL", "count": 60, "category": "后端开发",
     "modules": ["GraphQL概述", "Schema", "Query", "Mutation", "Subscription",
                 "Resolver", "类型系统", "指令", "缓存", "性能优化",
                 "安全", "工具链", "Apollo", "GraphQL最佳实践"]},
    {"name": "WebSocket", "count": 60, "category": "后端开发",
     "modules": ["WebSocket概述", "握手协议", "数据帧", "服务端实现", "客户端实现",
                 "心跳检测", "断线重连", "房间管理", "广播", "性能优化",
                 "安全", "负载均衡", "WebSocket最佳实践"]},
    {"name": "消息队列", "count": 100, "category": "后端开发",
     "modules": ["消息队列概述", "JMS", "AMQP", "Kafka", "RabbitMQ",
                 "RocketMQ", "Pulsar", "消息模型", "消息可靠性", "消息顺序",
                 "消息事务", "死信队列", "延迟队列", "性能优化", "最佳实践"]},
    {"name": "Django", "count": 80, "category": "后端开发",
     "modules": ["Django基础", "MTV架构", "URL路由", "视图", "模板",
                 "ORM", "表单", "认证", "Admin", "中间件",
                 "缓存", "信号", "REST Framework", "性能优化", "Django最佳实践"]},
    {"name": "Flask", "count": 60, "category": "后端开发",
     "modules": ["Flask基础", "路由", "视图", "模板", "请求响应",
                 "蓝图", "扩展", "数据库", "认证", "测试",
                 "部署", "Flask最佳实践"]},

    # ===== 数据与存储（10个）=====
    {"name": "数据库原理", "count": 120, "category": "数据存储",
     "modules": ["数据库概述", "关系模型", "SQL", "关系代数", "范式",
                 "事务ACID", "并发控制", "锁机制", "索引", "查询优化",
                 "存储引擎", "日志", "备份恢复", "分布式数据库", "NoSQL",
                 "NewSQL", "数据库最佳实践"]},
    {"name": "MySQL", "count": 200, "category": "数据存储",
     "modules": ["MySQL基础", "架构", "存储引擎", "InnoDB", "MyISAM",
                 "索引原理", "SQL优化", "执行计划", "事务", "锁",
                 "主从复制", "读写分离", "分库分表", "高可用", "备份恢复",
                 "性能调优", "监控", "安全", "MySQL最佳实践"]},
    {"name": "Redis", "count": 120, "category": "数据存储",
     "modules": ["Redis基础", "数据结构", "String", "Hash", "List",
                 "Set", "ZSet", "Bitmap", "HyperLogLog", "Geo",
                 "Stream", "持久化", "主从复制", "哨兵", "集群",
                 "缓存设计", "分布式锁", "限流", "性能优化", "Redis最佳实践"]},
    {"name": "PostgreSQL", "count": 100, "category": "数据存储",
     "modules": ["PostgreSQL基础", "架构", "数据类型", "索引", "查询优化",
                 "事务", "MVCC", "锁", "扩展", "全文检索",
                 "JSON", "GIS", "复制", "高可用", "性能调优",
                 "备份恢复", "PostgreSQL最佳实践"]},
    {"name": "MongoDB", "count": 80, "category": "数据存储",
     "modules": ["MongoDB基础", "文档模型", "CRUD", "索引", "聚合",
                 "复制集", "分片", "事务", "性能优化", "安全",
                 "备份恢复", "MongoDB最佳实践"]},
    {"name": "Elasticsearch", "count": 100, "category": "数据存储",
     "modules": ["ES基础", "架构", "索引", "文档", "映射",
                 "查询DSL", "聚合", "分词", "集群", "分片",
                 "性能优化", "高可用", "安全", "ELK栈", "ES最佳实践"]},
    {"name": "数据仓库", "count": 80, "category": "数据存储",
     "modules": ["数据仓库概述", "维度建模", "星型雪花", "事实表", "维度表",
                 "ETL", "分层架构", "OLAP", "指标体系", "数据治理",
                 "性能优化", "Hive", "ClickHouse", "Doris", "数据仓库最佳实践"]},
    {"name": "缓存技术", "count": 80, "category": "数据存储",
     "modules": ["缓存概述", "缓存策略", "缓存穿透", "缓存击穿", "缓存雪崩",
                 "缓存一致性", "本地缓存", "分布式缓存", "多级缓存", "缓存预热",
                 "缓存降级", "热点key", "大key", "性能优化", "缓存最佳实践"]},
    {"name": "ETL开发", "count": 60, "category": "数据存储",
     "modules": ["ETL概述", "数据抽取", "数据转换", "数据加载", "数据清洗",
                 "数据质量", "调度", "增量同步", "CDC", "性能优化",
                 "工具", "ETL最佳实践"]},
    {"name": "时序数据库", "count": 60, "category": "数据存储",
     "modules": ["时序数据概述", "InfluxDB", "Prometheus", "TimescaleDB", "TDengine",
                 "数据模型", "写入优化", "查询优化", "降采样", "保留策略",
                 "时序数据库最佳实践"]},

    # ===== DevOps与云（10个）=====
    {"name": "Docker", "count": 100, "category": "DevOps",
     "modules": ["Docker基础", "镜像", "容器", "Dockerfile", "网络",
                 "存储", "数据卷", "Compose", "Registry", "多阶段构建",
                 "安全", "性能优化", "日志", "监控", "最佳实践"]},
    {"name": "Kubernetes", "count": 200, "category": "DevOps",
     "modules": ["K8s基础", "架构", "Pod", "Deployment", "Service",
                 "Volume", "ConfigMap", "Secret", "Namespace", "Ingress",
                 "StatefulSet", "DaemonSet", "Job", "CronJob", "RBAC",
                 "网络策略", "资源限制", "调度", "Helm", "Operator",
                 "监控", "日志", "安全", "性能优化", "K8s最佳实践"]},
    {"name": "CI与CD", "count": 80, "category": "DevOps",
     "modules": ["CI/CD概述", "持续集成", "持续交付", "持续部署", "流水线",
                 "Jenkins", "GitLab CI", "GitHub Actions", "ArgoCD", "制品管理",
                 "自动化测试", "部署策略", "回滚", "安全", "CI/CD最佳实践"]},
    {"name": "Git版本控制", "count": 80, "category": "DevOps",
     "modules": ["Git基础", "版本控制", "分支", "合并", "变基",
                 "工作流", "GitFlow", "GitHub Flow", "标签", "储藏",
                 "子模块", "大文件", "冲突解决", "历史改写", "Git最佳实践"]},
    {"name": "Linux运维", "count": 100, "category": "DevOps",
     "modules": ["Linux基础", "用户管理", "权限管理", "进程管理", "服务管理",
                 "软件包", "网络配置", "防火墙", "磁盘管理", "文件系统",
                 "日志管理", "定时任务", "Shell脚本", "性能监控", "故障排查",
                 "安全加固", "Linux运维最佳实践"]},
    {"name": "监控告警", "count": 80, "category": "DevOps",
     "modules": ["监控概述", "指标监控", "日志监控", "链路追踪", "Prometheus",
                 "Grafana", "AlertManager", "Zabbix", "APM", "告警设计",
                 "SLA/SLO", "容量规划", "性能分析", "监控最佳实践"]},
    {"name": "日志分析", "count": 60, "category": "DevOps",
     "modules": ["日志概述", "日志采集", "日志存储", "日志检索", "日志分析",
                 "ELK栈", "EFK栈", "Loki", "日志告警", "日志安全",
                 "日志最佳实践"]},
    {"name": "Nginx", "count": 80, "category": "DevOps",
     "modules": ["Nginx基础", "架构", "配置", "虚拟主机", "反向代理",
                 "负载均衡", "静态资源", "缓存", "SSL/TLS", "HTTP/2",
                 "限流", "访问控制", "日志", "性能优化", "Nginx最佳实践"]},
    {"name": "云计算", "count": 60, "category": "DevOps",
     "modules": ["云计算概述", "IaaS", "PaaS", "SaaS", "公有云",
                 "私有云", "混合云", "阿里云", "AWS", "云原生",
                 "云安全", "成本优化", "云计算最佳实践"]},
    {"name": "Ansible", "count": 60, "category": "DevOps",
     "modules": ["Ansible基础", "Inventory", "Ad-Hoc", "Playbook", "Role",
                 "模块", "变量", "模板", "条件循环", "标签",
                 "Vault", "最佳实践"]},

    # ===== 安全（8个）=====
    {"name": "网络安全", "count": 100, "category": "安全",
     "modules": ["网络安全概述", "网络攻击", "网络防御", "防火墙", "IDS/IPS",
                 "VPN", "网络隔离", "DDoS防护", "端口扫描", "嗅探",
                 "协议安全", "无线安全", "安全审计", "应急响应", "网络安全最佳实践"]},
    {"name": "Web安全", "count": 120, "category": "安全",
     "modules": ["Web安全概述", "XSS", "CSRF", "SQL注入", "命令注入",
                 "文件上传", "文件包含", "SSRF", "XXE", "反序列化",
                 "越权", "逻辑漏洞", "会话管理", "认证安全", "CORS",
                 "HTTPS", "CSP", "安全头", "WAF", "代码审计",
                 "渗透测试", "Web安全最佳实践"]},
    {"name": "密码学", "count": 100, "category": "安全",
     "modules": ["密码学概述", "对称加密", "DES", "AES", "非对称加密",
                 "RSA", "ECC", "哈希函数", "MD5", "SHA",
                 "消息认证码", "数字签名", "证书", "PKI", "密钥交换",
                 "随机数", "密码协议", "TLS/SSL", "PGP", "密码学最佳实践"]},
    {"name": "渗透测试", "count": 100, "category": "安全",
     "modules": ["渗透测试概述", "信息收集", "漏洞扫描", "社会工程学", "漏洞利用",
                 "提权", "横向移动", "持久化", "痕迹清除", "报告编写",
                 "Metasploit", "Burp Suite", "Nmap", "Kali Linux", "渗透测试最佳实践"]},
    {"name": "逆向工程", "count": 80, "category": "安全",
     "modules": ["逆向概述", "汇编基础", "PE文件", "ELF文件", "调试器",
                 "反汇编", "反编译", "IDA Pro", "Ghidra", "OllyDbg",
                 "脱壳", "加密算法识别", "补丁", "逆向分析", "逆向最佳实践"]},
    {"name": "漏洞挖掘", "count": 60, "category": "安全",
     "modules": ["漏洞概述", "漏洞分类", "漏洞挖掘方法", "Fuzzing", "代码审计",
                 "二进制审计", "漏洞利用", "Shellcode", "ROP", "漏洞报告",
                 "漏洞挖掘最佳实践"]},
    {"name": "移动安全", "count": 60, "category": "安全",
     "modules": ["移动安全概述", "Android安全", "iOS安全", "APP逆向", "APP加固",
                 "通信安全", "数据存储安全", "权限管理", "恶意软件分析", "移动安全最佳实践"]},
    {"name": "云安全", "count": 60, "category": "安全",
     "modules": ["云安全概述", "云安全责任", "身份管理", "数据安全", "网络安全",
                 "容器安全", "K8s安全", "云安全工具", "合规", "云安全最佳实践"]},

    # ===== AI与算法（8个）=====
    {"name": "数据结构与算法", "count": 200, "category": "AI与算法",
     "modules": ["算法概述", "复杂度分析", "数组", "链表", "栈",
                 "队列", "哈希表", "树", "二叉树", "平衡树",
                 "堆", "图", "排序", "查找", "递归",
                 "分治", "动态规划", "贪心", "回溯", "图算法",
                 "字符串算法", "高级数据结构", "算法设计", "算法最佳实践"]},
    {"name": "机器学习", "count": 150, "category": "AI与算法",
     "modules": ["ML概述", "监督学习", "无监督学习", "线性回归", "逻辑回归",
                 "决策树", "随机森林", "SVM", "KNN", "朴素贝叶斯",
                 "KMeans", "DBSCAN", "PCA", "特征工程", "模型评估",
                 "交叉验证", "超参数调优", "集成学习", "XGBoost", "LightGBM",
                 "推荐系统", "ML最佳实践"]},
    {"name": "深度学习", "count": 120, "category": "AI与算法",
     "modules": ["DL概述", "神经网络", "反向传播", "激活函数", "损失函数",
                 "优化器", "CNN", "RNN", "LSTM", "GRU",
                 "Attention", "Transformer", "GAN", "AutoEncoder", "迁移学习",
                 "正则化", "批归一化", "深度学习框架", "PyTorch", "TensorFlow",
                 "DL最佳实践"]},
    {"name": "自然语言处理", "count": 100, "category": "AI与算法",
     "modules": ["NLP概述", "文本预处理", "分词", "词向量", "Word2Vec",
                 "GloVe", "语言模型", "N-gram", "文本分类", "情感分析",
                 "命名实体识别", "关系抽取", "机器翻译", "文本生成", "问答系统",
                 "BERT", "GPT", "大语言模型", "NLP最佳实践"]},
    {"name": "计算机视觉", "count": 100, "category": "AI与算法",
     "modules": ["CV概述", "图像处理", "图像滤波", "边缘检测", "特征提取",
                 "SIFT", "ORB", "图像分类", "目标检测", "YOLO",
                 "Faster R-CNN", "图像分割", "语义分割", "实例分割", "人脸识别",
                 "OCR", "视频分析", "数据增强", "CV最佳实践"]},
    {"name": "强化学习", "count": 60, "category": "AI与算法",
     "modules": ["RL概述", "MDP", "值函数", "Q-Learning", "SARSA",
                 "策略梯度", "DQN", "PPO", "Actor-Critic", "蒙特卡洛",
                 "时序差分", "多智能体", "RL最佳实践"]},
    {"name": "数据挖掘", "count": 80, "category": "AI与算法",
     "modules": ["数据挖掘概述", "数据预处理", "关联规则", "Apriori", "FP-Growth",
                 "聚类", "分类", "回归", "异常检测", "序列模式",
                 "文本挖掘", "Web挖掘", "推荐算法", "数据挖掘最佳实践"]},
    {"name": "知识图谱", "count": 60, "category": "AI与算法",
     "modules": ["知识图谱概述", "本体建模", "知识抽取", "实体识别", "关系抽取",
                 "知识融合", "知识推理", "图数据库", "Neo4j", "知识图谱应用",
                 "知识图谱最佳实践"]},

    # ===== 其他领域（8个）=====
    {"name": "区块链", "count": 80, "category": "其他",
     "modules": ["区块链概述", "密码学基础", "共识机制", "POW", "POS",
                 "智能合约", "Solidity", "以太坊", "比特币", "DApp",
                 "DeFi", "NFT", "跨链", "钱包", "区块链安全",
                 "区块链最佳实践"]},
    {"name": "游戏开发", "count": 100, "category": "其他",
     "modules": ["游戏开发概述", "游戏引擎", "Unity", "Unreal", "游戏循环",
                 "场景管理", "物理引擎", "碰撞检测", "动画", "粒子系统",
                 "渲染", "光照", "材质", "音频", "AI",
                 "网络同步", "性能优化", "游戏最佳实践"]},
    {"name": "计算机图形学", "count": 80, "category": "其他",
     "modules": ["图形学概述", "线性代数", "坐标变换", "渲染管线", "光栅化",
                 "着色器", "光照模型", "纹理映射", "深度测试", "抗锯齿",
                 "阴影", "全局光照", "光线追踪", "OpenGL", "Vulkan",
                 "图形学最佳实践"]},
    {"name": "音视频处理", "count": 80, "category": "其他",
     "modules": ["音视频概述", "音频基础", "视频基础", "编码原理", "H.264",
                 "H.265", "AAC", "MP4", "FLV", "HLS",
                 "RTMP", "WebRTC", "FFmpeg", "音视频同步", "流媒体",
                 "音视频最佳实践"]},
    {"name": "物联网", "count": 60, "category": "其他",
     "modules": ["IoT概述", "传感器", "嵌入式", "通信协议", "MQTT",
                 "CoAP", "LoRa", "NB-IoT", "边缘计算", "物联网平台",
                 "物联网安全", "物联网最佳实践"]},
    {"name": "低代码开发", "count": 50, "category": "其他",
     "modules": ["低代码概述", "可视化开发", "表单设计", "流程设计", "数据建模",
                 "API集成", "权限管理", "部署发布", "低代码平台", "低代码最佳实践"]},
    {"name": "量子计算", "count": 50, "category": "其他",
     "modules": ["量子计算概述", "量子比特", "量子门", "量子电路", "量子算法",
                 "Shor算法", "Grover算法", "量子纠缠", "量子纠错", "量子编程",
                 "量子计算最佳实践"]},
    {"name": "Rust系统编程", "count": 50, "category": "其他",
     "modules": ["Rust系统编程概述", "内存安全", "所有权", "生命周期", "unsafe",
                 "FFI", "嵌入式Rust", "操作系统开发", "WebAssembly", "Rust系统编程最佳实践"]},
    {"name": "大语言模型", "count": 150, "category": "AI与算法",
     "modules": ["LLM概述", "Transformer架构", "注意力机制", "预训练", "微调",
                 "指令微调", "RLHF", "Prompt工程", "上下文学习", "思维链",
                 "RAG检索增强", "Agent", "工具调用", "多模态", "模型评估",
                 "推理优化", "量化", "蒸馏", "部署", "LLM最佳实践"]},
    {"name": "AIGC", "count": 100, "category": "AI与算法",
     "modules": ["AIGC概述", "文本生成", "图像生成", "Diffusion模型", "Stable Diffusion",
                 "Midjourney", "视频生成", "音频生成", "3D生成", "多模态生成",
                 "生成模型评估", "AIGC应用", "AIGC工具", "AIGC安全", "AIGC最佳实践"]},
    {"name": "微前端", "count": 80, "category": "前端开发",
     "modules": ["微前端概述", "架构设计", "qiankun", "single-spa", "Module Federation",
                 "应用隔离", "样式隔离", "JS沙箱", "通信机制", "路由分发",
                 "生命周期", "部署", "性能优化", "微前端最佳实践"]},
    {"name": "数据可视化", "count": 100, "category": "前端开发",
     "modules": ["可视化概述", "图表类型", "D3.js", "ECharts", "AntV",
                 "Three.js", "WebGL", "Canvas", "SVG", "地图可视化",
                 "大屏可视化", "交互设计", "性能优化", "可视化最佳实践"]},
    {"name": "自动化测试", "count": 100, "category": "后端开发",
     "modules": ["测试概述", "单元测试", "集成测试", "端到端测试", "Jest",
                 "Pytest", "JUnit", "Selenium", "Cypress", "Playwright",
                 "Mock", "测试覆盖率", "CI测试", "测试策略", "自动化测试最佳实践"]},
    {"name": "性能测试", "count": 80, "category": "后端开发",
     "modules": ["性能测试概述", "负载测试", "压力测试", "并发测试", "JMeter",
                 "Locust", "Gatling", "性能指标", "性能分析", "性能调优",
                 "瓶颈定位", "性能测试最佳实践"]},
    {"name": "代码重构", "count": 80, "category": "后端开发",
     "modules": ["重构概述", "坏味道识别", "提取函数", "内联函数", "提取变量",
                 "重命名", "移动函数", "数据重组", "条件逻辑简化", "多态替换条件",
                 "重构模式", "安全重构", "重构工具", "重构最佳实践"]},
    {"name": "设计模式", "count": 100, "category": "后端开发",
     "modules": ["设计模式概述", "创建型模式", "单例", "工厂方法", "抽象工厂",
                 "建造者", "原型", "结构型模式", "适配器", "装饰器",
                 "代理", "外观", "桥接", "组合", "享元",
                 "行为型模式", "策略", "观察者", "命令", "迭代器",
                 "模板方法", "状态", "访问者", "中介者", "备忘录",
                 "解释器", "责任链", "设计模式最佳实践"]},
]

if __name__ == "__main__":
    print(f"领域总数: {len(DOMAINS_CONFIG)}")
    total = sum(d['count'] for d in DOMAINS_CONFIG)
    print(f"知识点总数: {total}")
    categories = {}
    for d in DOMAINS_CONFIG:
        categories.setdefault(d['category'], []).append(d['name'])
    for cat, domains in categories.items():
        print(f"\n{cat} ({len(domains)}个):")
        for name in domains:
            count = next(d['count'] for d in DOMAINS_CONFIG if d['name'] == name)
            print(f"  - {name}: {count}个")
