# -*- coding: utf-8 -*-
"""KB expansion part 2: ML, DL, NLP, CV, RL, LLM, AIGC, data mining, knowledge graph."""

EXPANDED_KB_P2: dict[str, dict] = {
    "ML概述": {"focus": "机器学习范式与工程流程", "c1": ("范式", "监督（标签）、无监督（无标签）、半监督、强化学习。"), "c2": ("流程", "数据 → 特征 → 模型 → 训练 → 评估 → 部署 → 监控。"), "c3": ("偏差-方差", "欠拟合（高偏差）与过拟合（高方差）的权衡。"), "mech": "定义问题 → 收集数据 → 选模型 → 训练验证 → 部署。"},
    "监督学习": {"focus": "监督学习问题类型与算法", "c1": ("分类", "输出离散标签：垃圾邮件、图像分类。"), "c2": ("回归", "输出连续值：房价预测、销量预测。"), "c3": ("算法", "线性/逻辑回归、决策树、SVM、神经网络。"), "mech": "标注数据 → 特征提取 → 模型训练 → 损失最小化 → 预测。"},
    "无监督学习": {"focus": "无监督学习与应用", "c1": ("聚类", "K-Means、DBSCAN 发现数据分组。"), "c2": ("降维", "PCA、t-SNE 可视化高维数据。"), "c3": ("异常检测", "Isolation Forest、One-Class SVM。"), "mech": "无标签数据 → 发现结构/模式 → 应用。"},
    "线性回归": {"focus": "线性回归模型与最小二乘", "c1": ("模型", "y = w·x + b，最小化 MSE。"), "c2": ("解析解", "正规方程 w=(XᵀX)⁻¹Xᵀy。"), "c3": ("正则", "Ridge(L2) 防过拟合，Lasso(L1) 特征选择。"), "mech": "特征标准化 → 梯度下降/正规方程 → 评估 R²/RMSE。"},
    "逻辑回归": {"focus": "逻辑回归与分类", "c1": ("Sigmoid", "将线性输出映射到 (0,1) 概率。"), "c2": ("损失", "交叉熵损失，凸优化保证全局最优。"), "c3": ("多分类", "Softmax 扩展，One-vs-Rest 策略。"), "mech": "线性组合 → Sigmoid → 交叉熵 → 梯度下降。"},
    "决策树": {"focus": "决策树构建与剪枝", "c1": ("分裂", "信息增益/基尼系数选择最优特征。"), "c2": ("过拟合", "预剪枝（限制深度）与后剪枝。"), "c3": ("优点", "可解释性强，处理非线性关系。"), "mech": "递归选择最优分裂 → 构建树 → 剪枝 → 预测。"},
    "随机森林": {"focus": "Bagging 集成与随机森林", "c1": ("Bagging", "Bootstrap 采样 + 多棵决策树投票。"), "c2": ("随机性", "每棵树随机选择特征子集分裂。"), "c3": ("OOB", "Out-of-Bag 误差估计泛化能力。"), "mech": "N 棵树独立训练 → 分类投票/回归平均 → 预测。"},
    "SVM": {"focus": "支持向量机原理", "c1": ("间隔", "最大化分类间隔，支持向量决定边界。"), "c2": ("核技巧", "RBF/多项式核映射到高维空间。"), "c3": ("参数", "C 控制误分类惩罚，gamma 控制 RBF 宽度。"), "mech": "找支持向量 → 构造超平面 → 核函数处理非线性。"},
    "KNN": {"focus": "K 近邻算法", "c1": ("原理", "预测时找 K 个最近邻居，多数投票/平均。"), "c2": ("距离", "欧氏、曼哈顿、余弦距离。"), "c3": ("注意", "需特征标准化，计算复杂度 O(n)。"), "mech": "计算距离 → 选 K 近邻 → 投票/平均。"},
    "朴素贝叶斯": {"focus": "朴素贝叶斯分类器", "c1": ("贝叶斯", "P(y|x) ∝ P(x|y)P(y)，特征条件独立假设。"), "c2": ("类型", "高斯（连续）、多项式（计数）、伯努利（二值）。"), "c3": ("应用", "文本分类、垃圾邮件过滤。"), "mech": "统计先验与条件概率 → 贝叶斯公式 → 分类。"},
    "KMeans": {"focus": "K-Means 聚类", "c1": ("算法", "初始化中心 → 分配 → 更新中心 → 迭代至收敛。"), "c2": ("K 选择", "肘部法则、轮廓系数。"), "c3": ("局限", "需预设 K，对非球形簇效果差。"), "mech": "随机初始化 → E步分配 → M步更新 → 收敛。"},
    "DBSCAN": {"focus": "密度聚类 DBSCAN", "c1": ("原理", "基于密度连通性，不需预设簇数。"), "c2": ("参数", "eps 邻域半径，min_samples 最小点数。"), "c3": ("优势", "发现任意形状簇，识别噪声点。"), "mech": "核心点 → 密度可达 → 形成簇 → 噪声标记。"},
    "PCA": {"focus": "主成分分析降维", "c1": ("原理", "找方差最大的正交方向作为新轴。"), "c2": ("步骤", "标准化 → 协方差矩阵 → 特征分解 → 选前 k 个。"), "c3": ("应用", "可视化、去噪、特征压缩。"), "mech": "数据中心化 → SVD/特征分解 → 投影到主成分。"},
    "特征工程": {"focus": "特征工程技巧", "c1": ("处理", "缺失值填充、异常值处理、编码（One-Hot/Label）。"), "c2": ("构造", "交叉特征、多项式特征、时间特征。"), "c3": ("选择", "过滤法、包裹法、嵌入法。"), "mech": "理解数据 → 清洗 → 构造 → 选择 → 验证效果。"},
    "模型评估": {"focus": "分类与回归评估指标", "c1": ("分类", "Accuracy、Precision、Recall、F1、AUC-ROC。"), "c2": ("回归", "MSE、RMSE、MAE、R²。"), "c3": ("不平衡", "F1/AUC 优于 Accuracy。"), "mech": "划分测试集 → 计算指标 → 分析混淆矩阵。"},
    "交叉验证": {"focus": "K-Fold 与交叉验证", "c1": ("K-Fold", "K 折划分，每折轮流作验证集。"), "c2": ("Stratified", "保持类别比例的分层 K-Fold。"), "c3": ("LOOCV", "Leave-One-Out，N 小样本时使用。"), "mech": "K 折划分 → 训练 K 次 → 平均性能 → 选模型。"},
    "超参数调优": {"focus": "网格搜索与贝叶斯优化", "c1": ("Grid Search", "穷举参数组合。"), "c2": ("Random Search", "随机采样，效率更高。"), "c3": ("Optuna", "贝叶斯优化自动调参。"), "mech": "定义搜索空间 → 交叉验证评估 → 选最优参数。"},
    "集成学习": {"focus": "Bagging、Boosting 与 Stacking", "c1": ("Bagging", "并行训练，降低方差（随机森林）。"), "c2": ("Boosting", "串行训练，降低偏差（XGBoost/AdaBoost）。"), "c3": ("Stacking", "多层模型组合，元学习器融合。"), "mech": "选基学习器 → 组合策略 → 训练 → 融合预测。"},
    "XGBoost": {"focus": "XGBoost 梯度提升", "c1": ("原理", "加法模型，逐棵树拟合残差梯度。"), "c2": ("正则", "L1/L2 正则防过拟合。"), "c3": ("工程", "并行、缺失值处理、剪枝。"), "mech": "初始化 → 迭代建树 → 梯度+Hessian → 正则化目标。"},
    "LightGBM": {"focus": "LightGBM 高效梯度提升", "c1": ("GOSS", "Gradient-based One-Side Sampling 加速。"), "c2": ("EFB", "Exclusive Feature Bundling 降维。"), "c3": ("对比", "比 XGBoost 更快，大数据首选。"), "mech": "直方图算法 → 叶子优先生长 → Leaf-wise 策略。"},
    "推荐系统": {"focus": "协同过滤与推荐算法", "c1": ("协同过滤", "User-CF 和 Item-CF 基于行为相似性。"), "c2": ("矩阵分解", "SVD/ALS 分解用户-物品矩阵。"), "c3": ("深度学习", "Wide&Deep、DeepFM 融合特征。"), "mech": "收集行为 → 建模偏好 → 生成推荐 → 评估 CTR。"},
    "ML最佳实践": {"focus": "机器学习工程最佳实践", "practices": ["数据质量优先于模型复杂度", "训练/验证/测试严格分离", "监控数据漂移与模型退化", "可解释性与公平性评估", "版本化数据与模型"]},
    # 深度学习
    "DL概述": {"focus": "深度学习发展历程与核心概念", "c1": ("突破", "2012 AlexNet 开启深度学习时代。"), "c2": ("优势", "自动特征学习，端到端训练。"), "c3": ("硬件", "GPU/TPU 加速矩阵运算。"), "mech": "数据 → 网络设计 → 前向传播 → 损失 → 反向传播 → 更新。"},
    "神经网络": {"focus": "人工神经网络基础", "c1": ("感知机", "单层线性分类器，多层可逼近任意函数。"), "c2": ("全连接", "每层神经元与上层全连接。"), "c3": ("Universal Approximation", "足够宽的单隐层网络可逼近连续函数。"), "mech": "输入 → 加权求和 → 激活 → 输出。"},
    "反向传播": {"focus": "反向传播算法", "c1": ("链式法则", "逐层计算梯度，从输出层到输入层。"), "c2": ("计算图", "自动微分框架构建计算图求导。"), "c3": ("梯度消失", "Sigmoid/Tanh 深层网络梯度趋零。"), "mech": "前向计算 → 计算损失 → 反向传播梯度 → 更新参数。"},
    "激活函数": {"focus": "常见激活函数", "c1": ("ReLU", "max(0,x)，计算简单，缓解梯度消失。"), "c2": ("GELU/Swish", "Transformer 常用平滑激活。"), "c3": ("Softmax", "多分类输出层，输出概率分布。"), "mech": "引入非线性 → 使网络能拟合复杂函数。"},
    "损失函数": {"focus": "常见损失函数", "c1": ("MSE", "回归任务均方误差。"), "c2": ("CrossEntropy", "分类任务交叉熵。"), "c3": ("Focal Loss", "解决类别不平衡。"), "mech": "预测 vs 真实 → 计算损失 → 反向传播优化。"},
    "优化器": {"focus": "SGD、Adam 等优化器", "c1": ("SGD", "随机梯度下降 + 动量。"), "c2": ("Adam", "自适应学习率，默认首选。"), "c3": ("AdamW", "解耦权重衰减，Transformer 训练标准。"), "mech": "计算梯度 → 更新一阶/二阶矩估计 → 调整参数。"},
    "CNN": {"focus": "卷积神经网络", "c1": ("卷积", "局部连接 + 权重共享，提取空间特征。"), "c2": ("池化", "Max/Avg Pooling 降采样。"), "c3": ("经典", "LeNet → AlexNet → VGG → ResNet。"), "mech": "卷积 → 激活 → 池化 → 全连接 → 分类。"},
    "RNN": {"focus": "循环神经网络", "c1": ("循环", "隐状态传递序列信息。"), "c2": ("BPTT", "通过时间反向传播。"), "c3": ("局限", "长序列梯度消失/爆炸。"), "mech": "h_t = f(W·x_t + U·h_{t-1}) → 逐步处理序列。"},
    "LSTM": {"focus": "长短期记忆网络", "c1": ("门控", "遗忘门、输入门、输出门控制信息流。"), "c2": ("Cell State", "长期记忆通道，缓解梯度消失。"), "c3": ("应用", "序列建模、时间序列预测。"), "mech": "门控机制选择性记忆/遗忘 → 处理长序列。"},
    "GRU": {"focus": "门控循环单元", "c1": ("简化", "合并 LSTM 遗忘门和输入门为更新门。"), "c2": ("参数", "比 LSTM 少，训练更快。"), "c3": ("效果", "多数任务与 LSTM 相当。"), "mech": "更新门 + 重置门 → 隐状态更新。"},
    "Attention": {"focus": "注意力机制", "c1": ("原理", "Query-Key-Value 加权求和。"), "c2": ("Self-Attention", "序列内部元素互相关注。"), "c3": ("优势", "并行计算，长距离依赖。"), "mech": "Q,K,V → softmax(QKᵀ/√d)V → 加权输出。"},
    "Transformer": {"focus": "Transformer 架构", "c1": ("结构", "Encoder-Decoder，纯 Attention 无 RNN。"), "c2": ("Multi-Head", "多组 Attention 并行。"), "c3": ("位置编码", "注入序列位置信息。"), "mech": "Embedding + PosEnc → N×(MHA + FFN) → 输出。"},
    "GAN": {"focus": "生成对抗网络", "c1": ("对抗", "Generator 生成 vs Discriminator 判别。"), "c2": ("训练", "极小极大博弈，纳什均衡。"), "c3": ("变体", "DCGAN、StyleGAN、CycleGAN。"), "mech": "G 生成假样本 → D 判别 → 交替训练。"},
    "AutoEncoder": {"focus": "自编码器", "c1": ("结构", "Encoder 压缩 → Decoder 重建。"), "c2": ("应用", "降维、去噪、异常检测。"), "c3": ("VAE", "变分自编码器，生成模型。"), "mech": "输入 → 编码 → 瓶颈 → 解码 → 重建损失。"},
    "迁移学习": {"focus": "预训练与微调", "c1": ("预训练", "大规模数据训练通用特征。"), "c2": ("微调", "小数据集调整顶层或全网络。"), "c3": ("策略", "冻结骨干 + 训练分类头。"), "mech": "加载预训练权重 → 替换任务头 → 微调训练。"},
    "正则化": {"focus": "L1/L2/Dropout 正则化", "c1": ("L2", "权重衰减，防止权重过大。"), "c2": ("Dropout", "训练时随机丢弃神经元。"), "c3": ("Early Stopping", "验证集性能不再提升时停止。"), "mech": "损失 + 正则项 → 限制模型复杂度 → 泛化。"},
    "批归一化": {"focus": "Batch Normalization", "c1": ("原理", "归一化每层输入，加速训练。"), "c2": ("效果", "允许更大学习率，轻微正则化。"), "c3": ("变体", "LayerNorm（Transformer）、GroupNorm。"), "mech": "mini-batch 均值/方差 → 归一化 → 缩放偏移。"},
    "深度学习框架": {"focus": "PyTorch vs TensorFlow", "c1": ("PyTorch", "动态图，研究首选，Pythonic。"), "c2": ("TensorFlow", "静态图→Eager，生产部署强。"), "c3": ("JAX", "函数式自动微分，Google 研究。"), "mech": "选框架 → 定义模型 → 训练循环 → 部署。"},
    "PyTorch": {"focus": "PyTorch 核心 API", "c1": ("Tensor", "类似 NumPy 的可微张量。"), "c2": ("nn.Module", "模型基类，定义 forward。"), "c3": ("DataLoader", "批量加载与打乱数据。"), "mech": "Dataset → DataLoader → model → loss → backward → step。"},
    "TensorFlow": {"focus": "TensorFlow/Keras 使用", "c1": ("Keras", "高级 API，Sequential/Functional。"), "c2": ("tf.data", "高效数据管道。"), "c3": ("TF Serving", "生产模型部署。"), "mech": "Keras 建模 → compile → fit → evaluate → export。"},
    "DL最佳实践": {"focus": "深度学习最佳实践", "practices": ["从简单模型开始", "监控训练/验证曲线", "学习率调度", "混合精度训练", "梯度裁剪防爆炸"]},
    # LLM
    "LLM概述": {"focus": "大语言模型发展历程", "c1": ("演进", "GPT-1 → GPT-3 → ChatGPT → GPT-4 → 开源 LLaMA/Qwen。"), "c2": ("能力", "文本生成、问答、推理、代码、工具调用。"), "c3": ("Scaling Law", "模型/数据/算力规模与性能正相关。"), "mech": "预训练 → 微调 → 对齐 → 部署 → 应用。"},
    "Transformer架构": {"focus": "LLM 中的 Transformer 细节", "c1": ("Decoder-only", "GPT 类模型仅使用 Decoder。"), "c2": ("RoPE", "旋转位置编码，现代 LLM 标准。"), "c3": ("SwiGLU", "SwiGLU FFN 替代标准 FFN。"), "mech": "Tokenize → Embedding → N×DecoderBlock → LM Head。"},
    "注意力机制": {"focus": "MHA、GQA 与 Flash Attention", "c1": ("MHA", "Multi-Head Attention 并行多组。"), "c2": ("GQA", "Grouped Query Attention 减少 KV 缓存。"), "c3": ("Flash Attention", "IO 感知精确 Attention，加速训练。"), "mech": "Q,K,V 投影 → Attention 计算 → 输出投影。"},
    "预训练": {"focus": "LLM 预训练", "c1": ("数据", "万亿 Token 网页/书籍/代码混合。"), "c2": ("目标", "Causal LM：预测下一个 Token。"), "c3": ("基础设施", "分布式训练、流水线并行、张量并行。"), "mech": "数据清洗 → Tokenize → 自回归训练 → Checkpoint。"},
    "微调": {"focus": "LLM 微调方法", "c1": ("Full FT", "全参数微调，效果最好但成本高。"), "c2": ("LoRA", "低秩适配，仅训练小矩阵。"), "c3": ("QLoRA", "量化 + LoRA，单卡微调大模型。"), "mech": "加载基座 → 准备数据 → 选微调方法 → 训练 → 评估。"},
    "指令微调": {"focus": "Instruction Tuning", "c1": ("数据", "Instruction-Response 对，如 Alpaca/ShareGPT。"), "c2": ("效果", "提升指令遵循与对话能力。"), "c3": ("格式", "Chat Template 统一对话格式。"), "mech": "构造指令数据 → SFT 训练 → 评估指令遵循。"},
    "RLHF": {"focus": "人类反馈强化学习", "c1": ("三步", "SFT → 训练 Reward Model → PPO 优化。"), "c2": ("Reward Model", "人类偏好排序训练奖励模型。"), "c3": ("DPO", "Direct Preference Optimization 简化 RLHF。"), "mech": "SFT 模型 → 收集偏好 → RM → RL 优化 → 对齐模型。"},
    "Prompt工程": {"focus": "Prompt 设计技巧", "c1": ("Zero-shot", "直接描述任务，不给示例。"), "c2": ("Few-shot", "提供几个示例引导模型。"), "c3": ("System Prompt", "设定角色与行为约束。"), "mech": "明确任务 → 提供上下文/示例 → 指定输出格式 → 迭代优化。"},
    "上下文学习": {"focus": "In-Context Learning", "c1": ("ICL", "无需梯度更新，上下文示例即「学习」。"), "c2": ("机制", "模型从示例中提取任务模式。"), "c3": ("局限", "上下文窗口限制示例数量。"), "mech": "Prompt 中嵌入示例 → 模型推断模式 → 生成答案。"},
    "思维链": {"focus": "Chain-of-Thought 推理", "c1": ("CoT", "引导模型逐步推理：Let's think step by step。"), "c2": ("效果", "显著提升数学/逻辑推理准确率。"), "c3": ("变体", "Self-Consistency、Tree-of-Thought。"), "mech": "问题 → 分步推理 → 中间步骤 → 最终答案。"},
    "RAG检索增强": {"focus": "RAG 架构与实现", "c1": ("RAG", "Retrieval-Augmented Generation 检索+生成。"), "c2": ("流程", "Query → 检索相关文档 → 拼接 Prompt → LLM 生成。"), "c3": ("向量库", "Embedding → 向量数据库存储与检索。"), "mech": "文档切分 → Embedding → 索引 → 检索 → 增强 Prompt → 生成。"},
    "Agent": {"focus": "LLM Agent 架构", "c1": ("Agent", "LLM + 规划 + 工具 + 记忆。"), "c2": ("ReAct", "Reasoning + Acting 交替推理与行动。"), "c3": ("框架", "LangChain、AutoGPT、MetaGPT。"), "mech": "接收任务 → 规划步骤 → 调用工具 → 观察结果 → 迭代。"},
    "工具调用": {"focus": "Function Calling / Tool Use", "c1": ("Function Calling", "LLM 输出结构化工具调用请求。"), "c2": ("OpenAI Tools", "tools 参数定义可用函数。"), "c3": ("安全", "工具权限最小化，输入校验。"), "mech": "定义工具 Schema → LLM 决策 → 执行工具 → 返回结果。"},
    "多模态": {"focus": "多模态大模型", "c1": ("架构", "Vision Encoder + LLM 融合。"), "c2": ("模型", "GPT-4V、LLaVA、Qwen-VL。"), "c3": ("应用", "图像理解、文档 OCR、视觉问答。"), "mech": "图像编码 → 投影到 LLM 空间 → 联合推理。"},
    "模型评估": {"focus": "LLM 评估基准", "c1": ("基准", "MMLU、HumanEval、GSM8K、MT-Bench。"), "c2": ("人工评估", "Helpfulness、Harmlessness、Honesty。"), "c3": ("自动", "BLEU/ROUGE（生成）、Accuracy（选择）。"), "mech": "选基准 → 运行评估 → 分析错误 → 迭代改进。"},
    "推理优化": {"focus": "LLM 推理加速", "c1": ("KV Cache", "缓存已计算的 Key/Value。"), "c2": ("PagedAttention", "vLLM 分页管理 KV Cache。"), "c3": ("Speculative Decoding", "小模型草稿 + 大模型验证。"), "mech": "优化内存 → 批处理 → 量化 → 投机解码。"},
    "量化": {"focus": "模型量化", "c1": ("INT8/INT4", "降低权重精度，减少显存。"), "c2": ("GPTQ/AWQ", "训练后量化方法。"), "c3": ("效果", "4-bit 量化精度损失小，推理快 2-4x。"), "mech": "校准数据 → 量化权重 → 评估精度 → 部署。"},
    "蒸馏": {"focus": "知识蒸馏", "c1": ("蒸馏", "大模型（Teacher）指导小模型（Student）。"), "c2": ("方法", "软标签 + 硬标签联合训练。"), "c3": ("应用", "部署小模型降低成本。"), "mech": "Teacher 生成软标签 → Student 模仿 → 评估。"},
    "部署": {"focus": "LLM 生产部署", "c1": ("Serving", "vLLM、TGI、TensorRT-LLM。"), "c2": ("API", "OpenAI 兼容 API 封装。"), "c3": ("监控", "延迟、吞吐、Token 用量、内容安全。"), "mech": "模型导出 → Serving 框架 → API 网关 → 监控。"},
    "LLM最佳实践": {"focus": "LLM 应用最佳实践", "practices": ["Prompt 版本化管理", "RAG 提升事实准确性", "输出内容安全过滤", "监控幻觉与偏见", "成本控制（缓存/量化）"]},
    # AIGC
    "AIGC概述": {"focus": "AIGC 技术概览", "c1": ("范围", "文本/图像/视频/音频/3D 内容 AI 生成。"), "c2": ("技术", "GPT、Diffusion、GAN、NeRF。"), "c3": ("应用", "设计、营销、娱乐、教育。"), "mech": "选择模态 → 选模型 → 设计 Prompt/参数 → 生成 → 后处理。"},
    "文本生成": {"focus": "AI 文本生成", "c1": ("模型", "GPT-4、Claude、Qwen 等大语言模型。"), "c2": ("控制", "Temperature、Top-p 控制多样性。"), "c3": ("应用", "写作辅助、摘要、翻译、代码。"), "mech": "Prompt → LLM → 后处理 → 输出。"},
    "图像生成": {"focus": "AI 图像生成技术", "c1": ("技术", "Diffusion Model 是当前主流。"), "c2": ("控制", "Prompt、ControlNet、IP-Adapter。"), "c3": ("质量", "分辨率、步数、CFG Scale 影响。"), "mech": "文本编码 → 噪声去噪 → 解码图像。"},
    "Diffusion模型": {"focus": "扩散模型原理", "c1": ("前向", "逐步加噪至纯噪声。"), "c2": ("反向", "神经网络学习去噪过程。"), "c3": ("DDPM/DDIM", "经典扩散模型与加速采样。"), "mech": "x_t = √α·x_{t-1} + √(1-α)·ε → 学习反向去噪。"},
    "Stable Diffusion": {"focus": "Stable Diffusion 使用", "c1": ("架构", "CLIP Text Encoder + UNet + VAE。"), "c2": ("Latent", "在潜空间扩散，降低计算量。"), "c3": ("生态", "ComfyUI、Automatic1111、LoRA 微调。"), "mech": "Prompt → CLIP → UNet 去噪 → VAE 解码 → 图像。"},
    "Midjourney": {"focus": "Midjourney 平台", "c1": ("特点", "Discord 交互，艺术风格强。"), "c2": ("Prompt", "简洁描述 + 风格参数 --style。"), "c3": ("对比", "闭源 SaaS vs 开源 SD。"), "mech": "Discord 输入 Prompt → 云端生成 → 选择变体。"},
    "视频生成": {"focus": "AI 视频生成", "c1": ("模型", "Sora、Runway Gen-2、Pika。"), "c2": ("技术", "时空 Attention、Video Diffusion。"), "c3": ("挑战", "时序一致性、物理合理性。"), "mech": "文本/图像 → 视频扩散 → 时序平滑 → 输出。"},
    "音频生成": {"focus": "AI 音频/音乐生成", "c1": ("TTS", "文字转语音：ElevenLabs、Azure TTS。"), "c2": ("音乐", "Suno、Udio AI 音乐生成。"), "c3": ("技术", "Audio Diffusion、AudioLM。"), "mech": "文本/条件 → 音频模型 → 波形/频谱 → 输出。"},
    "3D生成": {"focus": "AI 3D 内容生成", "c1": ("NeRF", "神经辐射场，多视角重建。"), "c2": ("3D Diffusion", "Direct 3D 生成，Point-E/Shap-E。"), "c3": ("应用", "游戏资产、产品展示。"), "mech": "文本/图像 → 3D 表示 → 渲染/导出。"},
    "多模态生成": {"focus": "跨模态生成", "c1": ("文生图/图生文", "CLIP 连接文本与视觉。"), "c2": ("Any-to-Any", "统一多模态生成模型。"), "c3": ("应用", "广告创意、产品原型。"), "mech": "多模态编码 → 统一生成 → 多模态输出。"},
    "生成模型评估": {"focus": "AIGC 质量评估", "c1": ("自动", "FID（图像）、IS、CLIP Score。"), "c2": ("人工", "美学评分、一致性、可用性。"), "c3": ("安全", "检测有害/虚假内容。"), "mech": "生成样本 → 多维度评估 → 迭代优化。"},
    "AIGC应用": {"focus": "AIGC 行业应用", "c1": ("设计", "海报、Logo、UI 原型。"), "c2": ("营销", "广告文案、产品图、短视频。"), "c3": ("开发", "代码生成、文档生成。"), "mech": "场景分析 → 选工具 → 工作流设计 → 人机协作。"},
    "AIGC工具": {"focus": "AIGC 工具链", "c1": ("图像", "SD、Midjourney、DALL-E、Firefly。"), "c2": ("文本", "ChatGPT、Claude、Copilot。"), "c3": ("工作流", "ComfyUI 节点式、LangChain Agent。"), "mech": "按需求选工具 → 组合工作流 → 自动化。"},
    "AIGC安全": {"focus": "AIGC 安全风险与治理", "c1": ("Deepfake", "虚假图像/视频/音频检测。"), "c2": ("版权", "训练数据版权与生成物归属。"), "c3": ("内容安全", "过滤有害、偏见、虚假信息。"), "mech": "输入过滤 → 生成监控 → 输出审核 → 水印溯源。"},
    "AIGC最佳实践": {"focus": "AIGC 最佳实践", "practices": ["明确版权与合规边界", "人工审核关键输出", "Prompt 工程提升质量", "建立品牌风格一致性", "关注内容安全与伦理"]},
}
