# -*- coding: utf-8 -*-
"""KB expansion part 3: NLP, CV, RL, data mining, KG, blockchain, game, graphics, AV, IoT, etc."""

EXPANDED_KB_P3: dict[str, dict] = {
    "NLP概述": {"focus": "自然语言处理任务与应用", "c1": ("任务", "分类、NER、翻译、摘要、问答、生成。"), "c2": ("演进", "规则 → 统计 → 深度学习 → 预训练 LM。"), "c3": ("挑战", "歧义、长文本、低资源语言。"), "mech": "文本输入 → 预处理 → 模型 → 任务输出。"},
    "文本预处理": {"focus": "文本清洗与规范化", "c1": ("清洗", "去 HTML、特殊字符、统一编码。"), "c2": ("规范化", "大小写、繁简、全半角。"), "c3": ("中文", "无空格分词，需专门分词工具。"), "mech": "原始文本 → 清洗 → 规范化 → 分词 → 下游任务。"},
    "分词": {"focus": "中英文分词", "c1": ("中文", "jieba、HanLP、LTP 基于词典/统计/深度学习。"), "c2": ("英文", "空格分词 + Stemming/Lemmatization。"), "c3": ("Subword", "BPE/WordPiece 用于 Transformer。"), "mech": "选分词器 → 处理 OOV → 输出 Token 序列。"},
    "词向量": {"focus": "词嵌入表示", "c1": ("One-Hot", "高维稀疏，无法表达语义相似。"), "c2": ("Dense", "低维稠密向量，语义相近词向量接近。"), "c3": ("上下文", "ELMo 上下文相关词向量。"), "mech": "词 → 查表/编码 → 稠密向量 → 下游使用。"},
    "Word2Vec": {"focus": "Word2Vec 模型", "c1": ("CBOW", "上下文预测中心词。"), "c2": ("Skip-gram", "中心词预测上下文。"), "c3": ("性质", "king - man + woman ≈ queen。"), "mech": "大规模语料 → 训练 → 词向量矩阵。"},
    "GloVe": {"focus": "GloVe 全局向量", "c1": ("原理", "全局词共现矩阵分解。"), "c2": ("对比", "Word2Vec 局部上下文 vs GloVe 全局统计。"), "c3": ("应用", "初始化 Embedding 层。"), "mech": "共现矩阵 → 加权最小二乘 → 词向量。"},
    "语言模型": {"focus": "语言模型基础", "c1": ("定义", "P(w1,w2,...,wn) 句子概率。"), "c2": ("用途", "语音识别、机器翻译、文本生成。"), "c3": ("困惑度", "Perplexity 评估 LM 质量。"), "mech": "链式法则分解 → 条件概率 → 连乘。"},
    "N-gram": {"focus": "N-gram 语言模型", "c1": ("Markov", "假设第 n 词仅依赖前 n-1 词。"), "c2": ("平滑", "Laplace/Good-Turing 处理零概率。"), "c3": ("局限", "数据稀疏，无法捕获长距离依赖。"), "mech": "统计 N-gram 频率 → 平滑 → 预测下一词。"},
    "文本分类": {"focus": "文本分类方法", "c1": ("传统", "TF-IDF + SVM/朴素贝叶斯。"), "c2": ("深度学习", "TextCNN、BiLSTM、BERT。"), "c3": ("评估", "Accuracy、F1、混淆矩阵。"), "mech": "文本 → 特征/Embedding → 分类器 → 标签。"},
    "情感分析": {"focus": "情感分析任务", "c1": ("粒度", "文档级、句子级、方面级（ABSA）。"), "c2": ("方法", "词典法、机器学习、预训练模型微调。"), "c3": ("应用", "评论分析、舆情监控。"), "mech": "文本 → 情感分类/评分 → 聚合分析。"},
    "命名实体识别": {"focus": "NER 序列标注", "c1": ("实体", "人名、地名、机构名、时间等。"), "c2": ("标注", "BIO/BIOES 标注方案。"), "c3": ("模型", "BiLSTM-CRF、BERT-CRF。"), "mech": "Token 序列 → 序列标注 → BIO 解码 → 实体。"},
    "关系抽取": {"focus": "实体关系抽取", "c1": ("任务", "从文本中提取实体间关系（如：创始人）。"), "c2": ("方法", "Pipeline（NER+RE）或 Joint 联合抽取。"), "c3": ("远程监督", "利用知识库自动标注训练数据。"), "mech": "文本 → 实体识别 → 关系分类 → 三元组。"},
    "机器翻译": {"focus": "神经机器翻译", "c1": ("Seq2Seq", "Encoder-Decoder + Attention。"), "c2": ("Transformer", "当前 NMT 标准架构。"), "c3": ("评估", "BLEU、COMET 自动评估。"), "mech": "源语言 → Encoder → Attention → Decoder → 目标语言。"},
    "文本生成": {"focus": "文本生成技术", "c1": ("方法", "GPT 自回归、T5 编码-解码。"), "c2": ("控制", "Prompt、Temperature、约束解码。"), "c3": ("评估", "BLEU、ROUGE、人工评估。"), "mech": "条件 → 自回归生成 Token → 解码文本。"},
    "问答系统": {"focus": "QA 系统架构", "c1": ("类型", "抽取式（从文档找答案）vs 生成式。"), "c2": ("RAG", "检索增强生成，结合知识库。"), "c3": ("评估", "Exact Match、F1（SQuAD）。"), "mech": "问题 → 检索/理解 → 答案抽取/生成。"},
    "BERT": {"focus": "BERT 预训练模型", "c1": ("MLM", "Masked Language Model 预训练。"), "c2": ("NSP", "Next Sentence Prediction（后续版本移除）。"), "c3": ("微调", "加任务头微调下游任务。"), "mech": "预训练 → 加载 → 加分类/标注头 → 微调。"},
    "GPT": {"focus": "GPT 系列模型", "c1": ("架构", "Decoder-only Transformer。"), "c2": ("预训练", "Causal LM：预测下一 Token。"), "c3": ("能力", "Few-shot 学习，无需微调。"), "mech": "Token 序列 → 自回归生成 → 文本输出。"},
    "NLP最佳实践": {"focus": "NLP 工程最佳实践", "practices": ["中文分词选合适工具", "预训练模型优先", "评估用多个指标", "注意训练/测试数据泄露", "监控线上模型效果"]},
    # CV
    "CV概述": {"focus": "计算机视觉任务概览", "c1": ("任务", "分类、检测、分割、跟踪、OCR。"), "c2": ("演进", "手工特征 → CNN → Transformer（ViT）。"), "c3": ("应用", "安防、医疗、自动驾驶、工业。"), "mech": "图像输入 → 预处理 → 模型 → 视觉理解输出。"},
    "图像处理": {"focus": "基础图像处理", "c1": ("操作", "缩放、旋转、裁剪、颜色空间转换。"), "c2": ("OpenCV", "cv2 是 Python 图像处理标准库。"), "c3": ("归一化", "像素值归一化到 [0,1] 或标准化。"), "mech": "读取 → 预处理 → 增强 → 输入模型。"},
    "图像滤波": {"focus": "空间域滤波", "c1": ("平滑", "均值滤波、高斯滤波去噪。"), "c2": ("锐化", "拉普拉斯、Unsharp Masking。"), "c3": ("中值", "中值滤波去椒盐噪声。"), "mech": "卷积核 → 滑动窗口 → 像素加权求和。"},
    "边缘检测": {"focus": "边缘检测算法", "c1": ("Sobel", "一阶导数近似，检测梯度。"), "c2": ("Canny", "多步骤：高斯→梯度→非极大抑制→双阈值。"), "c3": ("应用", "轮廓提取、特征检测前置。"), "mech": "灰度图 → 梯度计算 → 阈值 → 边缘图。"},
    "特征提取": {"focus": "图像特征描述", "c1": ("传统", "SIFT、SURF、ORB 关键点+描述子。"), "c2": ("深度学习", "CNN 中间层特征图。"), "c3": ("用途", "匹配、检索、跟踪。"), "mech": "检测关键点 → 计算描述子 → 匹配/索引。"},
    "SIFT": {"focus": "SIFT 特征", "c1": ("步骤", "DoG 尺度空间 → 关键点 → 方向 → 描述子。"), "c2": ("不变性", "尺度、旋转不变。"), "c3": ("专利", "2020 年专利过期，可自由使用。"), "mech": "多尺度 → 极值点 → 128 维描述子。"},
    "ORB": {"focus": "ORB 快速特征", "c1": ("组成", "FAST 关键点 + BRIEF 描述子。"), "c2": ("优势", "免费、快速，适合实时。"), "c3": ("旋转", "Steered BRIEF 实现旋转不变。"), "mech": "FAST 检测 → 方向计算 → BRIEF 描述。"},
    "图像分类": {"focus": "图像分类模型", "c1": ("ResNet", "残差连接解决深层退化。"), "c2": ("EfficientNet", "复合缩放平衡深度/宽度/分辨率。"), "c3": ("ViT", "Vision Transformer 纯 Attention。"), "mech": "图像 → Backbone → 全局池化 → FC → 类别。"},
    "目标检测": {"focus": "目标检测方法", "c1": ("Two-stage", "R-CNN 系列：候选区域 + 分类。"), "c2": ("One-stage", "YOLO/SSD：直接回归框+类别。"), "c3": ("指标", "mAP（mean Average Precision）。"), "mech": "图像 → 特征 → 框回归 + 分类 → NMS。"},
    "YOLO": {"focus": "YOLO 系列检测器", "c1": ("YOLOv8", "当前主流，Anchor-free。"), "c2": ("速度", "实时检测，适合视频流。"), "c3": ("训练", "Ultralytics 框架简单易用。"), "mech": "Grid 划分 → 每格预测框 → 置信度过滤 → NMS。"},
    "Faster R-CNN": {"focus": "Faster R-CNN 架构", "c1": ("RPN", "Region Proposal Network 生成候选框。"), "c2": ("RoI Pooling", "对齐特征到固定大小。"), "c3": ("精度", "Two-stage 精度通常更高。"), "mech": "Backbone → RPN → RoI Align → 分类+回归。"},
    "图像分割": {"focus": "语义/实例/全景分割", "c1": ("语义", "每像素分类，不区分实例。"), "c2": ("实例", "检测+分割每个物体。"), "c3": ("全景", "语义+实例统一。"), "mech": "Encoder-Decoder → 逐像素预测 → 后处理。"},
    "语义分割": {"focus": "语义分割模型", "c1": ("FCN", "全卷积网络，端到端分割。"), "c2": ("U-Net", "编码-解码+跳跃连接，医学常用。"), "c3": ("DeepLab", "空洞卷积增大感受野。"), "mech": "Encoder 降采样 → Decoder 上采样 → 像素分类。"},
    "实例分割": {"focus": "实例分割 Mask R-CNN", "c1": ("Mask R-CNN", "Faster R-CNN + 分割分支。"), "c2": ("输出", "每个实例的 bounding box + mask。"), "c3": ("应用", "物体计数、机器人抓取。"), "mech": "检测 → RoI Align → 分类+框+Mask。"},
    "人脸识别": {"focus": "人脸识别流程", "c1": ("检测", "MTCNN/RetinaFace 检测人脸。"), "c2": ("对齐", "关键点对齐标准化。"), "c3": ("识别", "ArcFace/CosFace 特征+比对。"), "mech": "检测 → 对齐 → 特征提取 → 1:1/1:N 比对。"},
    "OCR": {"focus": "光学字符识别", "c1": ("流程", "文本检测 → 文本识别。"), "c2": ("检测", "EAST/DBNet 检测文本区域。"), "c3": ("识别", "CRNN/Transformer 序列识别。"), "mech": "图像 → 检测框 → 裁剪 → 识别 → 文本。"},
    "视频分析": {"focus": "视频理解", "c1": ("任务", "动作识别、目标跟踪、视频摘要。"), "c2": ("3D CNN", "I3D、SlowFast 时空特征。"), "c3": ("Transformer", "Video Transformer 长程建模。"), "mech": "帧序列 → 时空特征 → 时序建模 → 预测。"},
    "数据增强": {"focus": "图像数据增强", "c1": ("几何", "翻转、旋转、缩放、裁剪。"), "c2": ("颜色", "亮度、对比度、色调抖动。"), "c3": ("高级", "Mixup、CutMix、AutoAugment。"), "mech": "训练时随机增强 → 提升泛化 → 减少过拟合。"},
    "CV最佳实践": {"focus": "计算机视觉最佳实践", "practices": ["数据增强提升泛化", "预训练模型迁移", "mAP 多阈值评估", "注意标注质量", "部署考虑推理速度"]},
    # RL
    "RL概述": {"focus": "强化学习基本概念", "c1": ("要素", "Agent、Environment、State、Action、Reward。"), "c2": ("目标", "最大化累积奖励。"), "c3": ("探索", "Exploration vs Exploitation 权衡。"), "mech": "Agent 观察 State → 选 Action → 获 Reward → 更新策略。"},
    "MDP": {"focus": "马尔可夫决策过程", "c1": ("Markov", "未来仅依赖当前状态。"), "c2": ("要素", "S, A, P, R, γ（折扣因子）。"), "c3": ("策略", "π(a|s) 状态到动作的映射。"), "mech": "定义 MDP → 求解最优策略 π*。"},
    "值函数": {"focus": "状态值与动作值函数", "c1": ("V(s)", "状态 s 的期望累积奖励。"), "c2": ("Q(s,a)", "状态 s 执行动作 a 的期望累积奖励。"), "c3": ("Bellman", "Bellman 方程递归定义值函数。"), "mech": "V(s) = max_a [R + γΣP(s'|s,a)V(s')]。"},
    "Q-Learning": {"focus": "Q-Learning 算法", "c1": ("Off-policy", "学习最优 Q 而不遵循当前策略。"), "c2": ("更新", "Q(s,a) ← Q(s,a) + α[r + γ max Q(s',a') - Q(s,a)]。"), "c3": ("表格", "小状态空间用 Q-Table。"), "mech": "交互 → 存储经验 → Q 值更新 → 贪婪策略。"},
    "SARSA": {"focus": "SARSA On-policy 算法", "c1": ("On-policy", "学习当前策略的 Q 值。"), "c2": ("更新", "使用实际执行的 a' 而非 max。"), "c3": ("对比", "SARSA 更保守，Q-Learning 更激进。"), "mech": "Q(s,a) ← Q(s,a) + α[r + γQ(s',a') - Q(s,a)]。"},
    "策略梯度": {"focus": "策略梯度方法", "c1": ("直接", "参数化策略 π_θ，梯度上升优化。"), "c2": ("REINFORCE", "蒙特卡洛策略梯度。"), "c3": ("高方差", "需 Baseline 或 Actor-Critic 降低。"), "mech": "采样轨迹 → 计算回报 → ∇J(θ) → 更新 θ。"},
    "DQN": {"focus": "Deep Q-Network", "c1": ("经验回放", "存储转移，随机采样打破相关性。"), "c2": ("目标网络", "固定目标 Q 网络稳定训练。"), "c3": ("突破", "Atari 游戏超越人类。"), "mech": "CNN 估计 Q → 经验回放 → 目标网络 → ε-greedy。"},
    "PPO": {"focus": "Proximal Policy Optimization", "c1": ("Clip", "限制策略更新幅度，稳定训练。"), "c2": ("优势", "比 TRPO 简单，效果相当。"), "c3": ("应用", "OpenAI 机器人、ChatGPT RLHF。"), "mech": "采样 → 计算 Advantage → Clip 目标 → 多 epoch 更新。"},
    "Actor-Critic": {"focus": "Actor-Critic 架构", "c1": ("Actor", "策略网络，选动作。"), "c2": ("Critic", "值网络，评估状态/动作。"), "c3": ("A2C/A3C", "同步/异步 Advantage Actor-Critic。"), "mech": "Actor 选动作 → Critic 评估 → Advantage → 更新两者。"},
    "蒙特卡洛": {"focus": "蒙特卡洛方法", "c1": ("MC", "完整 episode 采样估计值函数。"), "c2": ("特点", "无偏但高方差，仅 episodic 任务。"), "c3": ("Every-visit", "每个状态每次访问都更新。"), "mech": "完整 episode → 计算回报 G → 更新 V/Q。"},
    "时序差分": {"focus": "TD 学习", "c1": ("TD(0)", "V(s) ← V(s) + α[r + γV(s') - V(s)]。"), "c2": ("优势", "无需等 episode 结束，在线学习。"), "c3": ("TD(λ)", "Eligibility Trace 多步回报。"), "mech": "一步转移 → TD 误差 → 更新值函数。"},
    "多智能体": {"focus": "多智能体强化学习", "c1": ("MARL", "多 Agent 同时学习，环境非平稳。"), "c2": ("合作/竞争", "Team reward vs 零和博弈。"), "c3": ("方法", "Independent Q、MADDPG、QMIX。"), "mech": "多 Agent 交互 → 联合/独立策略 → 协调/竞争。"},
    "RL最佳实践": {"focus": "强化学习最佳实践", "practices": ["Reward 设计是关键", "从简单环境开始", "监控训练曲线", "Seed 影响大需多次实验", "Sim-to-Real 注意域差距"]},
    # 数据挖掘 & 知识图谱
    "数据挖掘概述": {"focus": "数据挖掘流程与 CRISP-DM", "c1": ("CRISP-DM", "业务理解→数据理解→准备→建模→评估→部署。"), "c2": ("任务", "关联、分类、聚类、异常、预测。"), "c3": ("与ML", "数据挖掘侧重发现模式，ML 侧重预测。"), "mech": "业务问题 → 数据 → 挖掘算法 → 模式/模型 → 应用。"},
    "数据预处理": {"focus": "数据清洗与转换", "c1": ("缺失", "删除、均值/中位数填充、模型预测。"), "c2": ("异常", "3σ、IQR、Isolation Forest。"), "c3": ("转换", "归一化、离散化、编码。"), "mech": "原始数据 → 清洗 → 转换 → 质量检查 → 建模。"},
    "关联规则": {"focus": "关联规则挖掘", "c1": ("指标", "Support（支持度）、Confidence（置信度）、Lift。"), "c2": ("应用", "购物篮分析、推荐。"), "c3": ("冗余", "高 Support 规则可能显然。"), "mech": "事务数据 → 频繁项集 → 生成规则 → 筛选。"},
    "Apriori": {"focus": "Apriori 算法", "c1": ("原理", "频繁项集的子集也频繁（反单调性）。"), "c2": ("步骤", "逐层搜索 k-项频繁集。"), "c3": ("局限", "多次扫描数据库，大数据慢。"), "mech": "1-项集 → 连接剪枝 → k-项集 → 直到为空。"},
    "FP-Growth": {"focus": "FP-Growth 算法", "c1": ("FP-Tree", "压缩存储频繁项，避免候选生成。"), "c2": ("优势", "比 Apriori 快，只需两次扫描。"), "c3": ("挖掘", "递归构建条件 FP-Tree。"), "mech": "构建 FP-Tree → 递归挖掘 → 频繁模式。"},
    "聚类": {"focus": "聚类算法对比", "c1": ("K-Means", "球形簇，需预设 K。"), "c2": ("层次", "Agglomerative/Divisive 树状结构。"), "c3": ("密度", "DBSCAN 任意形状。"), "mech": "选算法 → 预处理 → 聚类 → 评估（轮廓系数）。"},
    "分类": {"focus": "分类算法应用", "c1": ("算法", "决策树、SVM、神经网络、集成。"), "c2": ("评估", "Accuracy、AUC、F1。"), "c3": ("不平衡", "SMOTE 过采样、类权重。"), "mech": "标注数据 → 训练分类器 → 评估 → 部署。"},
    "回归": {"focus": "回归分析", "c1": ("线性", "最小二乘、Ridge/Lasso。"), "c2": ("非线性", "多项式、决策树、神经网络。"), "c3": ("评估", "MSE、MAE、R²。"), "mech": "特征 → 回归模型 → 预测连续值。"},
    "异常检测": {"focus": "异常检测方法", "c1": ("统计", "3σ、箱线图。"), "c2": ("ML", "Isolation Forest、One-Class SVM、AutoEncoder。"), "c3": ("应用", "欺诈检测、设备故障。"), "mech": "正常数据建模 → 偏离正常 → 标记异常。"},
    "序列模式": {"focus": "序列模式挖掘", "c1": ("GSP", "Generalized Sequential Pattern。"), "c2": ("PrefixSpan", "前缀投影高效挖掘。"), "c3": ("应用", "用户行为序列、DNA 序列。"), "mech": "序列数据库 → 频繁子序列 → 模式。"},
    "文本挖掘": {"focus": "文本数据挖掘", "c1": ("任务", "主题模型（LDA）、关键词提取、情感。"), "c2": ("LDA", "Latent Dirichlet Allocation 主题模型。"), "c3": ("TF-IDF", "关键词权重计算。"), "mech": "文本集合 → 特征提取 → 挖掘模型 → 模式。"},
    "Web挖掘": {"focus": "Web 数据挖掘", "c1": ("类型", "Web 内容/结构/使用挖掘。"), "c2": ("PageRank", "链接分析排序算法。"), "c3": ("日志", "用户行为分析、点击流。"), "mech": "爬取/日志 → 清洗 → 分析 → 洞察。"},
    "推荐算法": {"focus": "推荐系统算法", "c1": ("CF", "协同过滤 User/Item-based。"), "c2": ("CB", "内容基于特征匹配。"), "c3": ("Hybrid", "混合多种方法。"), "mech": "用户行为 → 建模偏好 → 生成推荐列表。"},
    "数据挖掘最佳实践": {"focus": "数据挖掘最佳实践", "practices": ["理解业务目标再选方法", "数据质量决定上限", "避免过拟合验证", "结果可解释性", "持续监控模型"]},
    "知识图谱概述": {"focus": "知识图谱概念与应用", "c1": ("定义", "实体-关系-实体三元组构成的语义网络。"), "c2": ("应用", "搜索、问答、推荐、金融风控。"), "c3": ("代表", "Google KG、Wikidata、企业知识库。"), "mech": "本体设计 → 知识获取 → 存储 → 应用。"},
    "本体建模": {"focus": "领域本体设计", "c1": ("本体", "概念、属性、关系的形式化定义。"), "c2": ("工具", "Protégé 本体编辑器。"), "c3": ("标准", "RDF、OWL 语义网标准。"), "mech": "领域分析 → 概念层次 → 属性关系 → OWL 定义。"},
    "知识抽取": {"focus": "知识图谱构建", "c1": ("来源", "结构化/半结构化/非结构化数据。"), "c2": ("方法", "规则、机器学习、远程监督。"), "c3": ("流水线", "抽取 → 融合 → 质量控制。"), "mech": "数据源 → NER/RE → 三元组 → 入库。"},
    "实体识别": {"focus": "KG 实体识别", "c1": ("方法", "词典、CRF、BERT-NER。"), "c2": ("领域", "通用 vs 领域实体（医疗/金融）。"), "c3": ("链接", "Entity Linking 消歧到 KG 实体。"), "mech": "文本 → NER → 实体链接 → KG 节点。"},
    "关系抽取": {"focus": "KG 关系抽取", "c1": ("方法", "模式匹配、远程监督、BERT。"), "c2": ("开放", "Open IE 开放域关系抽取。"), "c3": ("质量", "置信度过滤低质量三元组。"), "mech": "实体对 → 关系分类 → 三元组 → 验证。"},
    "知识融合": {"focus": "多源知识融合", "c1": ("实体对齐", "不同来源同一实体的识别。"), "c2": ("冲突", "矛盾事实的消解策略。"), "c3": ("质量", "来源可信度加权。"), "mech": "多源三元组 → 实体对齐 → 冲突消解 → 统一 KG。"},
    "知识推理": {"focus": "KG 推理", "c1": ("规则", "IF-THEN 规则推导新事实。"), "c2": ("嵌入", "TransE/RotatE 向量空间推理。"), "c3": ("GNN", "图神经网络在 KG 上推理。"), "mech": "已知三元组 → 推理规则/模型 → 新三元组。"},
    "图数据库": {"focus": "图数据库选型", "c1": ("Neo4j", "属性图，Cypher 查询语言。"), "c2": ("JanusGraph", "分布式大图存储。"), "c3": ("对比", "图数据库 vs 关系数据库多表 JOIN。"), "mech": "节点+边存储 → 图遍历查询 → 高效关系查询。"},
    "Neo4j": {"focus": "Neo4j 使用", "c1": ("Cypher", "MATCH (a)-[r]->(b) RETURN a,b 模式匹配。"), "c2": ("索引", "节点属性索引加速查询。"), "c3": ("APOC", "扩展过程库。"), "mech": "建模 → 导入 → Cypher 查询 → 可视化。"},
    "知识图谱应用": {"focus": "KG 应用场景", "c1": ("搜索", "语义搜索、知识卡片。"), "c2": ("问答", "KBQA 基于 KG 的问答。"), "c3": ("风控", "关联关系发现风险。"), "mech": "KG 构建 → 查询/推理 API → 上层应用。"},
    "知识图谱最佳实践": {"focus": "知识图谱最佳实践", "practices": ["本体设计先行", "质量优于数量", "持续更新维护", "与 NLP 结合自动化", "可视化辅助理解"]},
    # Web安全 渗透测试 module in Web domain
    "渗透测试": {"focus": "Web 应用渗透测试（授权）", "c1": ("范围", "Web 应用 PTES 测试，含 OWASP Testing Guide。"), "c2": ("流程", "信息收集 → 漏洞扫描 → 手工验证 → 报告。"), "c3": ("工具", "Burp Suite、OWASP ZAP（授权环境）。"), "mech": "授权确认 → 按 OWASP 测试 → 验证 → 报告。", "sec": "Web 渗透测试必须在书面授权范围内进行。"},
    # 云安全 网络安全 module
    "网络安全": {"focus": "云环境网络安全", "c1": ("VPC", "Virtual Private Cloud 网络隔离。"), "c2": ("Security Group", "虚拟防火墙规则。"), "c3": ("WAF", "云 WAF 防护 Web 应用。"), "mech": "VPC 设计 → 子网 → 安全组 → NACL → 监控。"},
    # 漏洞挖掘 sensitive
    "漏洞利用": {"focus": "漏洞验证原理（防御视角）", "c1": ("验证", "确认漏洞存在性的最小化验证。"), "c2": ("防御", "理解利用原理以设计防护。"), "c3": ("禁止", "不提供武器化 exploit 代码。"), "mech": "理解漏洞机制 → 设计防护 → 验证修复。", "sec": "仅讲解原理与防御，不提供利用代码。"},
    "Shellcode": {"focus": "Shellcode 概念（防御视角）", "c1": ("定义", "注入执行的机器码片段。"), "c2": ("防御", "DEP/NX、ASLR、Stack Canary。"), "c3": ("检测", "内存扫描、行为检测。"), "mech": "理解 Shellcode 原理 → 配置内存保护 → 检测异常。", "sec": "仅从防御角度讲解，不提供 Shellcode 编写。"},
    "ROP": {"focus": "ROP 攻击原理与防御", "c1": ("ROP", "Return-Oriented Programming 复用代码片段。"), "c2": ("防御", "CFI（Control Flow Integrity）。"), "c3": ("检测", "Stack 完整性监控。"), "mech": "理解 ROP 链 → 启用 CFI/DEP → 编译器保护。", "sec": "防御视角讲解，不提供 ROP 链构造。"},
    # 区块链
    "区块链概述": {"focus": "区块链原理与特点", "c1": ("特点", "去中心化、不可篡改、透明、共识。"), "c2": ("结构", "区块头 + 交易列表 + 哈希链。"), "c3": ("类型", "公链、联盟链、私链。"), "mech": "交易 → 打包区块 → 共识 → 上链 → 不可篡改。"},
    "密码学基础": {"focus": "区块链中的密码学", "c1": ("哈希", "SHA-256 链接区块。"), "c2": ("签名", "ECDSA 验证交易所有权。"), "c3": ("Merkle", "Merkle Tree 高效验证交易。"), "mech": "私钥签名 → 公钥验证 → 哈希链接。"},
    "共识机制": {"focus": "区块链共识算法", "c1": ("PoW", "工作量证明，比特币。"), "c2": ("PoS", "权益证明，以太坊 2.0。"), "c3": ("其他", "DPoS、PBFT、Raft。"), "mech": "提议区块 → 共识投票/计算 → 确认上链。"},
    "POW": {"focus": "工作量证明", "c1": ("挖矿", "寻找 nonce 使哈希满足难度。"), "c2": ("难度", "动态调整保持出块时间。"), "c3": ("51%攻击", "控制多数算力可篡改。"), "mech": "交易 → 挖矿竞争 → 最长链原则。"},
    "POS": {"focus": "权益证明", "c1": ("质押", "持有代币获得出块权。"), "c2": ("惩罚", "Slashing 恶意行为罚没质押。"), "c3": ("节能", "比 PoW 能耗低 99%+。"), "mech": "质押 → 随机选出块者 → 验证 → 奖励。"},
    "智能合约": {"focus": "智能合约概念", "c1": ("定义", "链上自动执行的代码。"), "c2": ("特点", "不可篡改、透明、自动执行。"), "c3": ("风险", "代码漏洞可导致资金损失。"), "mech": "部署合约 → 调用函数 → EVM 执行 → 状态变更。"},
    "Solidity": {"focus": "Solidity 编程", "c1": ("语法", "类似 JavaScript，面向合约。"), "c2": ("类型", "uint、address、mapping、struct。"), "c3": ("安全", "Reentrancy、Overflow 防护。"), "mech": "编写 → 编译 → 测试 → 部署 → 交互。"},
    "以太坊": {"focus": "Ethereum 平台", "c1": ("EVM", "Ethereum Virtual Machine 执行合约。"), "c2": ("Gas", "计算资源计量与费用。"), "c3": ("EIP", "Ethereum Improvement Proposal 标准。"), "mech": "账户模型 → 交易 → EVM → 状态更新。"},
    "比特币": {"focus": "Bitcoin 架构", "c1": ("UTXO", "Unspent Transaction Output 模型。"), "c2": ("脚本", "Bitcoin Script 验证交易。"), "c3": ("Halving", "每 21 万区块奖励减半。"), "mech": "UTXO → 交易构建 → 签名 → 广播 → 挖矿确认。"},
    "DApp": {"focus": "去中心化应用", "c1": ("架构", "前端 + Web3.js + 智能合约。"), "c2": ("钱包", "MetaMask 连接与签名。"), "c3": ("IPFS", "去中心化存储。"), "mech": "前端 → Web3 调用合约 → 钱包签名 → 链上执行。"},
    "DeFi": {"focus": "去中心化金融", "c1": ("协议", "Uniswap（DEX）、Aave（借贷）、Compound。"), "c2": ("AMM", "Automated Market Maker 自动做市。"), "c3": ("风险", "智能合约漏洞、无常损失。"), "mech": "连接钱包 → 交互 DeFi 协议 → 链上结算。"},
    "NFT": {"focus": "非同质化代币", "c1": ("ERC-721", "NFT 标准，唯一 Token ID。"), "c2": ("Metadata", "链下 JSON 描述属性。"), "c3": ("应用", "数字艺术、游戏道具、身份。"), "mech": "Mint → 元数据 → 交易 → 所有权转移。"},
    "跨链": {"focus": "跨链技术", "c1": ("桥", "Lock-Mint / Burn-Release 模式。"), "c2": ("协议", "Cosmos IBC、Polkadot XCMP。"), "c3": ("风险", "跨链桥是黑客重点目标。"), "mech": "源链锁定 → 中继证明 → 目标链铸造。"},
    "钱包": {"focus": "加密货币钱包", "c1": ("类型", "热钱包（在线）vs 冷钱包（离线）。"), "c2": ("密钥", "助记词 → 私钥 → 公钥 → 地址。"), "c3": ("安全", "私钥/助记词绝不上网。"), "mech": "生成密钥 → 备份助记词 → 签名交易。"},
    "区块链安全": {"focus": "区块链安全", "c1": ("合约", "审计、形式化验证、Bug Bounty。"), "c2": ("51%攻击", "PoW 算力攻击防护。"), "c3": ("前端", "钓鱼、签名欺骗防护。"), "mech": "代码审计 → 测试网验证 → 主网部署 → 监控。"},
    "区块链最佳实践": {"focus": "区块链开发最佳实践", "practices": ["智能合约安全审计", "测试网充分测试", "使用 OpenZeppelin 库", "私钥安全存储", "关注 Gas 优化"]},
    # 游戏开发
    "游戏开发概述": {"focus": "游戏开发流程与角色", "c1": ("流程", "概念→原型→生产→测试→发布→运营。"), "c2": ("角色", "策划、程序、美术、音效、QA。"), "c3": ("类型", "2D/3D、单机/网游、PC/移动/主机。"), "mech": "GDD → 原型 → 迭代开发 → 测试 → 发布。"},
    "游戏引擎": {"focus": "游戏引擎架构", "c1": ("组件", "渲染、物理、音频、输入、脚本、资源管理。"), "c2": ("选择", "Unity（通用）、Unreal（3A）、Godot（开源）。"), "c3": ("ECS", "Entity-Component-System 架构趋势。"), "mech": "引擎提供框架 → 开发者实现游戏逻辑。"},
    "Unity": {"focus": "Unity 引擎", "c1": ("语言", "C# 脚本。"), "c2": ("核心", "GameObject、Component、Prefab、Scene。"), "c3": ("生态", "Asset Store、URP/HDRP 渲染管线。"), "mech": "Scene → GameObject + Component → Script 逻辑。"},
    "Unreal": {"focus": "Unreal Engine", "c1": ("语言", "C++ + Blueprint 可视化脚本。"), "c2": ("渲染", "Nanite 几何、Lumen 全局光照。"), "c3": ("适用", "3A 大作、高画质项目。"), "mech": "Actor → Component → Blueprint/C++ 逻辑。"},
    "游戏循环": {"focus": "Game Loop 架构", "c1": ("循环", "Input → Update → Render → 重复。"), "c2": ("Delta Time", "帧率无关的物理/动画更新。"), "c3": ("Fixed Update", "固定时间步物理模拟。"), "mech": "while(running) { processInput(); update(dt); render(); }"},
    "场景管理": {"focus": "场景加载与管理", "c1": ("加载", "同步/异步场景加载。"), "c2": ("切换", "Scene Manager 管理场景栈。"), "c3": ("优化", "Additive Loading 分区加载。"), "mech": "场景设计 → 加载策略 → 切换逻辑 → 内存管理。"},
    "物理引擎": {"focus": "游戏物理模拟", "c1": ("引擎", "PhysX、Box2D、Bullet。"), "c2": ("组件", "Rigidbody、Collider、Joint。"), "c3": ("性能", "简化碰撞体、Sleep 静止物体。"), "mech": "物理世界 → 力/碰撞 → 积分更新 → 同步渲染。"},
    "碰撞检测": {"focus": "碰撞检测算法", "c1": ("Broad Phase", "空间划分（Octree/BVH）快速排除。"), "c2": ("Narrow Phase", "精确碰撞（GJK/SAT）。"), "c3": ("类型", "Box、Sphere、Mesh、Capsule。"), "mech": "粗检测 → 细检测 → 碰撞响应。"},
    "动画": {"focus": "游戏动画系统", "c1": ("骨骼", "Skeletal Animation 骨骼驱动网格。"), "c2": ("状态机", "Animator Controller 管理动画状态。"), "c3": ("Blend", "动画混合过渡。"), "mech": "骨骼 → 关键帧/程序化 → 蒙皮 → 渲染。"},
    "粒子系统": {"focus": "粒子特效", "c1": ("参数", "发射率、生命周期、速度、颜色、大小。"), "c2": ("模块", "Unity Particle System / Niagara。"), "c3": ("GPU", "GPU Particle 大量粒子。"), "mech": "Emitter → 粒子生成 → 更新 → 渲染。"},
    "渲染": {"focus": "游戏渲染管线", "c1": ("Forward", "前向渲染，简单场景。"), "c2": ("Deferred", "延迟渲染，多光源。"), "c3": ("PBR", "Physically Based Rendering 物理渲染。"), "mech": "几何 → 光照 → 阴影 → 后处理 → 输出。"},
    "光照": {"focus": "游戏光照", "c1": ("类型", "Directional/Point/Spot Light。"), "c2": ("烘焙", "Lightmap 预计算静态光照。"), "c3": ("实时", "Shadow Map、SSAO、GI。"), "mech": "光源 → 阴影 → 全局光照 → 最终颜色。"},
    "材质": {"focus": "材质与 Shader", "c1": ("PBR", "Metallic/Roughness 工作流。"), "c2": ("Shader", "顶点/片段着色器控制渲染。"), "c3": ("URP/HDRP", "Unity 可编程渲染管线。"), "mech": "Mesh + Material + Shader → GPU 渲染。"},
    "音频": {"focus": "游戏音频", "c1": ("类型", "BGM、SFX、Voice、Ambient。"), "c2": ("3D", "空间音频 HRTF。"), "c3": ("中间件", "FMOD、Wwise 专业音频引擎。"), "mech": "音频资源 → 播放管理 → 混音 → 输出。"},
    "AI": {"focus": "游戏 AI", "c1": ("行为树", "Behavior Tree 模块化 AI 逻辑。"), "c2": ("状态机", "FSM 简单 AI。"), "c3": ("寻路", "A*、NavMesh 导航。"), "mech": "感知 → 决策（BT/FSM）→ 行动 → 寻路。"},
    "网络同步": {"focus": "多人游戏网络", "c1": ("架构", "C/S、P2P、Dedicated Server。"), "c2": ("同步", "状态同步 vs 帧同步。"), "c3": ("延迟", "客户端预测、服务端 reconciliation。"), "mech": "输入 → 服务端模拟 → 状态同步 → 客户端渲染。"},
    "性能优化": {"focus": "游戏性能优化", "c1": ("CPU", "Profiler 找热点，对象池。"), "c2": ("GPU", "Draw Call 合批、LOD、Occlusion。"), "c3": ("内存", "资源卸载、纹理压缩。"), "mech": "Profiling → 瓶颈定位 → 优化 → 验证。"},
    "游戏最佳实践": {"focus": "游戏开发最佳实践", "practices": ["早期原型验证玩法", "模块化架构", "持续性能 Profiling", "版本控制+LFS", "自动化测试"]},
    # 计算机图形学
    "图形学概述": {"focus": "计算机图形学领域", "c1": ("分支", "渲染、建模、动画、可视化。"), "c2": ("管线", "应用 → 几何 → 光栅化 → 像素。"), "c3": ("API", "OpenGL、Vulkan、DirectX、Metal。"), "mech": "3D 模型 → 变换 → 渲染 → 2D 图像。"},
    "线性代数": {"focus": "图形学数学基础", "c1": ("向量", "点、方向、法线的表示与运算。"), "c2": ("矩阵", "旋转、缩放、平移的矩阵表示。"), "c3": ("变换", "Model-View-Projection 矩阵链。"), "mech": "局部坐标 → 世界 → 视图 → 裁剪 → 屏幕。"},
    "坐标变换": {"focus": "3D 坐标变换", "c1": ("Model", "物体局部到世界坐标。"), "c2": ("View", "世界到相机坐标。"), "c3": ("Projection", "透视/正交投影到裁剪空间。"), "mech": "P_clip = P_proj × P_view × P_model × P_local。"},
    "渲染管线": {"focus": "可编程渲染管线", "c1": ("阶段", "Vertex Shader → Rasterization → Fragment Shader。"), "c2": ("可编程", "GPU Shader 自定义渲染逻辑。"), "c3": ("Fixed", "早期固定管线已淘汰。"), "mech": "顶点 → 图元装配 → 光栅化 → 片段着色 → 输出。"},
    "光栅化": {"focus": "光栅化算法", "c1": ("三角形", "基本渲染图元。"), "c2": ("算法", "Edge Function、Bresenham。"), "c3": ("插值", "重心坐标插值顶点属性。"), "mech": "三角形 → 像素覆盖 → 深度/属性插值。"},
    "着色器": {"focus": "GLSL/HLSL 着色器", "c1": ("Vertex Shader", "顶点变换与属性传递。"), "c2": ("Fragment Shader", "像素颜色计算。"), "c3": ("Compute Shader", "GPGPU 通用计算。"), "mech": "Shader 源码 → 编译 → GPU 执行。"},
    "光照模型": {"focus": "光照与着色", "c1": ("Phong", "Ambient + Diffuse + Specular。"), "c2": ("Blinn-Phong", "半程向量优化。"), "c3": ("PBR", "基于物理的 Metallic/Roughness。"), "mech": "法线 · 光方向 → 漫反射 + 镜面反射。"},
    "纹理映射": {"focus": "UV 纹理映射", "c1": ("UV", "2D 纹理坐标映射到 3D 表面。"), "c2": ("过滤", "Nearest/Linear/Bilinear/Trilinear。"), "c3": ("Mipmap", "多级渐远纹理抗锯齿。"), "mech": "UV 坐标 → 纹理采样 → 混合颜色。"},
    "深度测试": {"focus": "Z-Buffer 深度测试", "c1": ("Z-Buffer", "每像素存储深度值。"), "c2": ("测试", "新片段深度 < 缓冲深度则通过。"), "c3": ("Early-Z", "提前深度测试优化。"), "mech": "渲染 → 深度比较 → 通过则写入颜色/深度。"},
    "抗锯齿": {"focus": "抗锯齿技术", "c1": ("MSAA", "多重采样抗锯齿。"), "c2": ("FXAA", "后处理快速抗锯齿。"), "c3": ("TAA", "时间抗锯齿，现代游戏常用。"), "mech": "边缘检测 → 多重采样/混合 → 平滑输出。"},
    "阴影": {"focus": "阴影映射", "c1": ("Shadow Map", "从光源渲染深度图。"), "c2": ("PCF", "Percentage Closer Filtering 软阴影。"), "c3": ("CSM", "Cascaded Shadow Maps 大场景。"), "mech": "光源视角深度 → 比较 → 阴影判定。"},
    "全局光照": {"focus": "全局光照方法", "c1": ("路径追踪", "Monte Carlo 路径采样。"), "c2": ("光子映射", "Photon Mapping 两遍算法。"), "c3": ("实时 GI", "Light Probe、SSGI、Lumen。"), "mech": "光线 → 多次反弹 → 累积颜色。"},
    "光线追踪": {"focus": "Ray Tracing", "c1": ("原理", "从相机发射光线，追踪相交。"), "c2": ("RTX", "NVIDIA 硬件加速光线追踪。"), "c3": ("Hybrid", "光栅 + RT 反射/阴影/GI。"), "mech": "Primary Ray → Intersect → Shade → Secondary Rays。"},
    "OpenGL": {"focus": "OpenGL API", "c1": ("状态机", "OpenGL 是状态机 API。"), "c2": ("Core Profile", "现代 OpenGL 3.3+ Core。"), "c3": ("工具", "GLFW + GLAD 窗口与加载。"), "mech": "上下文 → VAO/VBO → Shader → Draw Call。"},
    "Vulkan": {"focus": "Vulkan API", "c1": ("低开销", "显式控制，CPU 开销低。"), "c2": ("同步", "Fence、Semaphore、Pipeline Barrier。"), "c3": ("复杂", "比 OpenGL 复杂但性能更高。"), "mech": "Instance → Device → Swapchain → Command Buffer → Submit。"},
    "图形学最佳实践": {"focus": "图形学最佳实践", "practices": ["理解渲染管线各阶段", "从 OpenGL 入门再学 Vulkan", "Shader 调试工具", "性能分析 GPU Profiler", "PBR 工作流"]},
    # 音视频
    "音视频概述": {"focus": "音视频技术概览", "c1": ("链路", "采集→编码→传输→解码→渲染。"), "c2": ("标准", "H.264/H.265、AAC、MP4。"), "c3": ("应用", "直播、点播、视频会议、短视频。"), "mech": "采集 → 编码 → 封装 → 传输 → 解码 → 播放。"},
    "音频基础": {"focus": "数字音频基础", "c1": ("采样", "Nyquist 定理，采样率 ≥ 2×最高频率。"), "c2": ("量化", "位深度 16/24/32 bit。"), "c3": ("声道", "Mono/Stereo/5.1/7.1。"), "mech": "模拟信号 → ADC 采样 → PCM 数字音频。"},
    "视频基础": {"focus": "数字视频基础", "c1": ("帧率", "24/30/60 fps。"), "c2": ("分辨率", "720p/1080p/4K。"), "c3": ("色彩", "YUV 色彩空间，Y 亮度 UV 色度。"), "mech": "视频 = 帧序列 + 帧率 + 分辨率。"},
    "编码原理": {"focus": "音视频编码原理", "c1": ("压缩", "空间冗余（帧内）+ 时间冗余（帧间）。"), "c2": ("I/P/B帧", "I 关键帧，P 前向预测，B 双向预测。"), "c3": ("码率", "CBR 恒定 vs VBR 可变码率。"), "mech": "原始 → 预测 → 变换 → 量化 → 熵编码。"},
    "H.264": {"focus": "H.264/AVC 编码", "c1": ("Profile", "Baseline/Main/High Profile。"), "c2": ("应用", "最广泛支持的视频编码。"), "c3": ("工具", "x264 开源编码器。"), "mech": "宏块 → 帧内/帧间预测 → DCT → 量化 → CABAC。"},
    "H.265": {"focus": "H.265/HEVC 编码", "c1": ("效率", "比 H.264 节省 50% 码率。"), "c2": ("CTU", "Coding Tree Unit 最大 64×64。"), "c3": ("专利", "HEVC 专利池，AV1 免版税替代。"), "mech": "更大块 → 更多预测模式 → 更高压缩率。"},
    "AAC": {"focus": "AAC 音频编码", "c1": ("质量", "同码率优于 MP3。"), "c2": ("Profile", "LC-AAC、HE-AAC（低码率）。"), "c3": ("应用", "流媒体、MP4 默认音频。"), "mech": "MDCT → 量化 → 霍夫曼编码。"},
    "MP4": {"focus": "MP4 容器格式", "c1": ("结构", "Box/Atom 结构，ftmo/moov/mdat。"), "c2": ("流", "视频+音频+字幕多轨道。"), "c3": ("Fast Start", "moov 在 mdat 前支持流式播放。"), "mech": "编码流 → 封装 Box → MP4 文件。"},
    "FLV": {"focus": "FLV 格式", "c1": ("用途", "传统 RTMP 直播容器。"), "c2": ("结构", "Header + Tag（Video/Audio/Script）。"), "c3": ("现状", "逐渐被 HLS/DASH 替代。"), "mech": "编码 → FLV Tag 封装 → RTMP 推流。"},
    "HLS": {"focus": "HTTP Live Streaming", "c1": ("原理", "视频切 TS 分片 + m3u8 索引。"), "c2": ("自适应", "多码率 Variant Stream 切换。"), "c3": ("延迟", "LL-HLS 低延迟 HLS。"), "mech": "编码 → 切片 → m3u8 → HTTP 分发 → 播放。"},
    "RTMP": {"focus": "RTMP 协议", "c1": ("用途", "直播推流协议。"), "c2": ("流程", "推流端 → RTMP Server → 转码/分发。"), "c3": ("替代", "WebRTC、SRT 低延迟方案。"), "mech": "Handshake → Connect → Publish → 推流。"},
    "WebRTC": {"focus": "WebRTC 实时通信", "c1": ("组件", "getUserMedia + RTCPeerConnection + DataChannel。"), "c2": ("NAT", "STUN/TURN 穿透。"), "c3": ("信令", "SDP Offer/Answer 交换。"), "mech": "采集 → 编码 → P2P/SFU 传输 → 解码 → 渲染。"},
    "FFmpeg": {"focus": "FFmpeg 工具链", "c1": ("组件", "ffmpeg（转码）、ffprobe（信息）、ffplay（播放）。"), "c2": ("命令", "ffmpeg -i input -c:v libx264 output.mp4。"), "c3": ("滤镜", "scale、crop、overlay 滤镜链。"), "mech": "Demux → Decode → Filter → Encode → Mux。"},
    "音视频同步": {"focus": "A/V Sync", "c1": ("PTS/DTS", "Presentation/Decode Time Stamp。"), "c2": ("同步", "音频为主时钟，视频对齐。"), "c3": ("问题", "漂移、累积误差。"), "mech": "时间戳 → 缓冲 → 同步播放。"},
    "流媒体": {"focus": "流媒体架构", "c1": ("架构", "推流 → 源站 → CDN → 播放器。"), "c2": ("协议", "HLS/DASH/WebRTC。"), "c3": ("CDN", "边缘节点分发降低延迟。"), "mech": "采集推流 → 转码切片 → CDN 分发 → 客户端播放。"},
    "音视频最佳实践": {"focus": "音视频最佳实践", "practices": ["选合适编码参数", "FFmpeg 命令模板化", "监控卡顿/延迟", "多码率自适应", "WebRTC 信令安全"]},
    # IoT
    "IoT概述": {"focus": "物联网架构", "c1": ("层次", "感知层→网络层→平台层→应用层。"), "c2": ("规模", "数十亿设备连接。"), "c3": ("挑战", "安全、互操作、功耗、规模。"), "mech": "传感器 → 连接 → 平台 → 应用。"},
    "传感器": {"focus": "IoT 传感器", "c1": ("类型", "温湿度、光照、加速度、GPS。"), "c2": ("接口", "I2C、SPI、UART、GPIO。"), "c3": ("选型", "精度、量程、功耗、成本。"), "mech": "物理量 → 传感器 → ADC → 数字值。"},
    "嵌入式": {"focus": "IoT 嵌入式开发", "c1": ("平台", "ESP32、STM32、Arduino、Raspberry Pi。"), "c2": ("RTOS", "FreeRTOS、Zephyr 实时操作系统。"), "c3": ("开发", "C/C++、MicroPython。"), "mech": "硬件 → 驱动 → RTOS → 应用逻辑。"},
    "通信协议": {"focus": "IoT 通信协议", "c1": ("应用层", "MQTT、CoAP、HTTP。"), "c2": ("网络层", "Wi-Fi、BLE、LoRa、NB-IoT。"), "c3": ("选型", "距离、带宽、功耗、成本权衡。"), "mech": "设备 → 协议栈 → 网络 → 云端。"},
    "MQTT": {"focus": "MQTT 协议", "c1": ("模式", "Publish/Subscribe，Broker 中转。"), "c2": ("QoS", "0（最多一次）、1（至少一次）、2（恰好一次）。"), "c3": ("轻量", "Header 最小 2 字节，适合 IoT。"), "mech": "Client → Connect → Subscribe/Publish → Broker 转发。"},
    "CoAP": {"focus": "CoAP 协议", "c1": ("设计", "RESTful，类似 HTTP 但二进制轻量。"), "c2": ("UDP", "基于 UDP，低开销。"), "c3": ("Observe", "资源观察模式。"), "mech": "Client Request → Server Response → 资源操作。"},
    "LoRa": {"focus": "LoRa 远距离通信", "c1": ("特点", "远距离（km）、低带宽、低功耗。"), "c2": ("架构", "LoRa 终端 → Gateway → Network Server。"), "c3": ("应用", "智慧城市、农业监测。"), "mech": "LoRa 调制 → Gateway 汇聚 → 云端处理。"},
    "NB-IoT": {"focus": "NB-IoT 蜂窝物联网", "c1": ("特点", "广覆盖、低功耗、大连接。"), "c2": ("部署", "运营商基站升级。"), "c3": ("对比", "vs LoRa（私有网络）vs NB-IoT（运营商）。"), "mech": "NB-IoT 模块 → 基站 → 核心网 → 平台。"},
    "边缘计算": {"focus": "IoT 边缘计算", "c1": ("概念", "数据在靠近源头的边缘节点处理。"), "c2": ("优势", "低延迟、省带宽、离线能力。"), "c3": ("平台", "AWS Greengrass、Azure IoT Edge。"), "mech": "设备 → 边缘网关 → 本地处理 → 云端同步。"},
    "物联网平台": {"focus": "IoT 云平台", "c1": ("功能", "设备管理、数据采集、规则引擎、可视化。"), "c2": ("平台", "AWS IoT、阿里云 IoT、ThingsBoard。"), "c3": ("数字孪生", "设备数字化镜像。"), "mech": "设备接入 → 数据采集 → 规则触发 → 应用。"},
    "物联网安全": {"focus": "IoT 安全", "c1": ("威胁", "默认密码、固件漏洞、DDoS 僵尸网络。"), "c2": ("措施", "安全启动、加密通信、OTA 安全更新。"), "c3": ("标准", "OWASP IoT Top 10。"), "mech": "安全启动 → 加密通信 → 认证 → 更新。"},
    "物联网最佳实践": {"focus": "IoT 最佳实践", "practices": ["更改默认密码", "TLS 加密通信", "OTA 安全更新", "设备认证", "最小权限"]},
    # 低代码
    "低代码概述": {"focus": "低代码/无代码平台", "c1": ("定义", "可视化建模减少手写代码。"), "c2": ("场景", "企业内部系统、快速原型。"), "c3": ("局限", "复杂逻辑、性能、定制性。"), "mech": "可视化设计 → 自动生成 → 部署运行。"},
    "可视化开发": {"focus": "可视化开发方式", "c1": ("拖拽", "组件拖拽搭建界面。"), "c2": ("配置", "属性面板配置行为。"), "c3": ("预览", "实时预览开发效果。"), "mech": "组件库 → 拖拽布局 → 配置 → 预览。"},
    "表单设计": {"focus": "低代码表单", "c1": ("组件", "输入框、下拉、日期、上传。"), "c2": ("校验", "必填、格式、自定义规则。"), "c3": ("联动", "字段间显示/隐藏联动。"), "mech": "设计表单 → 配置校验 → 绑定数据 → 发布。"},
    "流程设计": {"focus": "工作流/审批流程", "c1": ("BPMN", "Business Process Model and Notation。"), "c2": ("节点", "开始、审批、条件、结束。"), "c3": ("引擎", "Flowable、Camunda 流程引擎。"), "mech": "流程图设计 → 部署 → 实例运行 → 监控。"},
    "数据建模": {"focus": "低代码数据模型", "c1": ("实体", "表/实体定义字段与关系。"), "c2": ("关系", "一对一、一对多、多对多。"), "c3": ("自动生成", "CRUD API 自动生成。"), "mech": "实体设计 → 关系定义 → 自动生成 API。"},
    "API集成": {"focus": "低代码 API 集成", "c1": ("连接器", "预置 SaaS 连接器（钉钉/企微）。"), "c2": ("REST", "自定义 REST API 调用。"), "c3": ("Webhook", "事件触发外部调用。"), "mech": "配置 API → 映射参数 → 测试 → 集成。"},
    "权限管理": {"focus": "低代码权限", "c1": ("RBAC", "角色-权限-用户。"), "c2": ("数据权限", "行级/列级数据过滤。"), "c3": ("审计", "操作日志追踪。"), "mech": "定义角色 → 分配权限 → 用户授权。"},
    "部署发布": {"focus": "低代码部署", "c1": ("环境", "开发/测试/生产多环境。"), "c2": ("发布", "一键发布/版本回滚。"), "c3": ("私有化", "本地部署 vs SaaS。"), "mech": "开发 → 测试 → 审批 → 生产发布。"},
    "低代码平台": {"focus": "主流低代码平台", "c1": ("国际", "OutSystems、Mendix、Power Apps。"), "c2": ("国内", "钉钉宜搭、飞书多维表格、简道云。"), "c3": ("选型", "场景、集成、成本、扩展性。"), "mech": "需求分析 → 平台选型 → POC → 实施。"},
    "低代码最佳实践": {"focus": "低代码最佳实践", "practices": ["简单场景优先", "保留代码扩展能力", "治理与版本管理", "安全审计", "评估长期 TCO"]},
    # 量子计算
    "量子计算概述": {"focus": "量子计算基础", "c1": ("量子比特", "Qubit 叠加态 |0⟩+|1⟩。"), "c2": ("优势", "特定问题指数加速。"), "c3": ("NISQ", "Noisy Intermediate-Scale Quantum 当前时代。"), "mech": "经典不可高效模拟 → 量子算法 → 量子硬件。"},
    "量子比特": {"focus": "Qubit 物理实现", "c1": ("实现", "超导、离子阱、光子、拓扑。"), "c2": ("叠加", "α|0⟩ + β|1⟩，|α|²+|β|²=1。"), "c3": ("测量", "测量坍缩到 |0⟩ 或 |1⟩。"), "mech": "初始化 → 量子操作 → 测量 → 经典结果。"},
    "量子门": {"focus": "量子逻辑门", "c1": ("单比特", "X（NOT）、H（Hadamard）、RZ。"), "c2": ("多比特", "CNOT、CZ 纠缠门。"), "c3": ("通用", "任意量子电路可由 H+T+CNOT 组合。"), "mech": "量子态 → 门操作（酉变换）→ 新量子态。"},
    "量子电路": {"focus": "量子线路设计", "c1": ("表示", "水平时间线，门从左到右。"), "c2": ("深度", "电路深度影响噪声累积。"), "c3": ("工具", "Qiskit Circuit、Quirk 可视化。"), "mech": "Qubit 线 → 排列门 → 测量 → 运行。"},
    "量子算法": {"focus": "量子算法概览", "c1": ("Shor", "大数分解，威胁 RSA。"), "c2": ("Grover", "无序搜索二次加速。"), "c3": ("VQE", "Variational Quantum Eigensolver 化学模拟。"), "mech": "问题编码 → 量子算法 → 测量 → 经典后处理。"},
    "Shor算法": {"focus": "Shor 大数分解", "c1": ("原理", "量子傅里叶变换找周期。"), "c2": ("影响", "足够量子比特可破解 RSA。"), "c3": ("应对", "后量子密码学（CRYSTALS-Kyber）。"), "mech": "选随机 a → 量子求周期 r → gcd(a^(r/2)±1, N) → 因子。"},
    "Grover算法": {"focus": "Grover 搜索", "c1": ("加速", "N 元素搜索 O(√N) 次查询。"), "c2": ("振幅放大", "标记目标态，反复反射放大。"), "c3": ("应用", "密码学密钥搜索（理论）。"), "mech": "均匀叠加 → Oracle 标记 → 扩散操作 → 迭代 → 测量。"},
    "量子纠缠": {"focus": "量子纠缠", "c1": ("Bell 态", "|Φ+⟩ = (|00⟩+|11⟩)/√2。"), "c2": ("非局域", "测量一个即时影响另一个。"), "c3": ("应用", "量子通信、量子密钥分发。"), "mech": "纠缠制备 → 分发 → 关联测量。"},
    "量子纠错": {"focus": "量子纠错码", "c1": ("问题", "量子噪声导致 decoherence。"), "c2": ("表面码", "Topological 纠错，Google 演示。"), "c3": ("阈值", "物理错误率低于阈值即可逻辑纠错。"), "mech": "冗余编码 → _syndrome 测量 → 纠错 → 逻辑 Qubit。"},
    "量子编程": {"focus": "Qiskit 量子编程", "c1": ("Qiskit", "IBM 开源量子框架。"), "c2": ("流程", "Circuit → Transpile → Backend → Result。"), "c3": ("模拟", "Aer 模拟器本地测试。"), "mech": "编写 Circuit → 模拟验证 → 提交量子硬件。"},
    "量子计算最佳实践": {"focus": "量子计算最佳实践", "practices": ["先模拟后硬件", "理解 NISQ 局限", "关注后量子密码", "线性代数基础", "从小电路开始"]},
    # Rust 系统编程
    "Rust系统编程概述": {"focus": "Rust 系统编程应用", "c1": ("领域", "OS、嵌入式、驱动、WebAssembly、高性能服务。"), "c2": ("优势", "内存安全 + 零成本抽象 + 并发安全。"), "c3": ("生态", "cargo、crates.io、tokio。"), "mech": "Rust 编译 → 原生二进制 / WASM → 部署。"},
    "内存安全": {"focus": "Rust 内存安全保证", "c1": ("编译期", "所有权系统编译期消除内存 bug。"), "c2": ("无 GC", "无垃圾回收，确定性性能。"), "c3": ("对比", "C 手动管理 vs Rust 编译器检查。"), "mech": "所有权规则 → 编译器检查 → 安全代码。"},
    "所有权": {"focus": "系统编程中的所有权", "c1": ("Move", "赋值/传参转移所有权。"), "c2": ("Copy", "栈上小类型自动复制。"), "c3": ("Drop", "RAII 自动释放资源。"), "mech": "每个值一个所有者 → 离开作用域 Drop。"},
    "生命周期": {"focus": "生命周期标注", "c1": ("标注", "'a 显式标注引用有效期。"), "c2": ("规则", "编译器推断 + 显式标注复杂场景。"), "c3": ("系统", "FFI 中生命周期管理更复杂。"), "mech": "引用 ≤ 被引用对象生命周期 → 编译通过。"},
    "unsafe": {"focus": "unsafe Rust", "c1": ("用途", "FFI、底层硬件、性能关键路径。"), "c2": ("责任", "程序员保证安全，编译器不检查。"), "c3": ("最小化", "unsafe 块尽可能小，封装安全 API。"), "mech": "unsafe { 原始指针/FFI/可变静态 } → 封装安全接口。"},
    "FFI": {"focus": "Rust 外部函数接口", "c1": ("C ABI", "extern \"C\" 互操作。"), "c2": ("bindgen", "自动生成 C 头文件绑定。"), "c3": ("安全", "封装 unsafe FFI 为 safe API。"), "mech": "C 库 → bindgen → Rust 绑定 → safe 封装。"},
    "嵌入式Rust": {"focus": "Rust 嵌入式开发", "c1": ("no_std", "无标准库，直接操作硬件。"), "c2": ("HAL", "embedded-hal 硬件抽象层。"), "c3": ("平台", "STM32、ESP32、nRF52。"), "mech": "HAL → 驱动 → 应用 → 交叉编译 → 烧录。"},
    "操作系统开发": {"focus": "Rust OS 开发", "c1": ("项目", "Redox OS、Tock OS。"), "c2": ("no_std", "裸机编程，自定义内存分配。"), "c3": ("引导", "bootloader + 内核。"), "mech": "bootloader → 内核初始化 → 驱动 → 用户空间。"},
    "WebAssembly": {"focus": "Rust 编译 WASM", "c1": ("wasm-pack", "Rust → WASM 工具链。"), "c2": ("用途", "浏览器高性能模块、插件系统。"), "c3": ("接口", "wasm-bindgen 与 JS 互操作。"), "mech": "Rust 代码 → wasm-pack build → WASM → JS 调用。"},
    "Rust系统编程最佳实践": {"focus": "Rust 系统编程最佳实践", "practices": ["最小化 unsafe 范围", "用 clippy/miri 检查", "FFI 封装 safe API", "no_std 注意内存分配", "交叉编译测试"]},
    # 大语言模型 in NLP domain
    "大语言模型": {"focus": "NLP 中的大语言模型", "c1": ("应用", "文本分类/NER 等任务的预训练+微调。"), "c2": ("模型", "BERT（Encoder）、GPT（Decoder）。"), "c3": ("趋势", "Prompt 工程 + 微调结合。"), "mech": "预训练 LM → 任务适配 → 推理部署。"},
}
