# -*- coding: utf-8 -*-
"""Hand-authored technical facts per (domain, module) — used to build full tutorial content."""

TECH: dict[tuple[str, str], dict] = {}

def T(domain, module, intro, mechanism, internals, workflow, performance, security,
      case_study, configuration, debugging, comparison, concepts, pitfalls, practices, ref0=""):
    TECH[(domain, module)] = {
        "intro": intro, "mechanism": mechanism, "internals": internals,
        "workflow": workflow, "performance": performance, "security": security,
        "case_study": case_study, "configuration": configuration,
        "debugging": debugging, "comparison": comparison,
        "concepts": concepts, "pitfalls": pitfalls, "practices": practices,
        "ref0": ref0,
    }

# ===================== C++ (15) =====================
T("C++", "C++基础",
  "C++ 在 C 上扩展类、命名空间、引用与函数重载；编译经预处理、翻译单元、名称修饰（name mangling）与链接。",
  "每个 .cpp 独立编译；链接器解析 mangled 符号；ODR 要求 inline 函数与模板定义可见。",
  "Clang AST → LLVM IR → 优化 → 机器码；Itanium ABI 规定 vtable 布局与 RTTI。",
  "源文件组织：.h 声明、.cpp 定义；namespace 防污染；using 声明谨慎。",
  "RAII 绑定资源生命周期；值语义默认拷贝，C++11 起移动语义减少分配。",
  "启用 -Wall -Wextra；智能指针替代裸 new/delete。",
  "构造函数显式 explicit 防隐式转换；Rule of Zero/Five 管理特殊成员。",
  "CMake 管理标准：set(CMAKE_CXX_STANDARD 17)。",
  "gdb/lldb 调试；sanitizer 家族 -fsanitize=address,undefined。",
  "相对 C：类型安全与抽象更强；相对 Rust：无编译期 borrow 检查。",
  [("命名空间", "namespace 隔离符号；匿名 namespace 内部链接。"), ("引用", "T& 必须绑定对象；const T& 绑定临时量延长生命。"),
   ("重载", "参数列表区分；不参与重载：返回类型。"), ("头文件", "#pragma once / include guard。")],
  [("using namespace std 在头文件", "污染全局。"), ("缺少 virtual 析构", "多态基类泄漏。"), ("成员初始化顺序", "按声明非初始化列表顺序。")],
  ["遵循 Core Guidelines", "优先 std 容器", "显式 explicit", "CI 跑 clang-tidy"],
  "cppreference.com — C++ 基础")

T("C++", "类与对象",
  "类将数据与操作封装；访问控制 public/protected/private；this 指针指向当前对象。",
  "编译器为每个类生成默认构造/拷贝/移动/析构（Rule of Five）；成员函数 implicit inline。",
  "对象内存：非虚类连续布局；vptr 在有多态虚函数时位于对象首部（实现定义）。",
  "定义类 → 实现 ctor/dtor → 成员函数 .cpp → 单元测试构造/赋值/析构路径。",
  "小对象值传递；大对象 const T&；移动构造转移资源所有权。",
  "成员 public 暴露 invariant 破坏面；const 成员函数保证逻辑 const。",
  "Pimpl idiom 隐藏实现细节，减编译依赖。",
  "=default/=delete 控制特殊成员生成。",
  "观察 ctor/dtor 顺序；AddressSanitizer 查 UAF。",
  "vs C struct：方法绑定类型；vs Java class：多继承与值语义。",
  [("构造与初始化", "初始化列表先于函数体；成员按声明顺序初始化。"), ("const 正确性", "const 方法不能改非 mutable 成员。"),
   ("static 成员", "类外定义存储；单例需注意线程安全。"), ("友元", "打破封装，谨慎使用。")],
  [("浅拷贝资源类", "双删；需 Rule of Five。"), ("在 ctor 调 virtual", "派生未构造。"), ("slice 对象", "值切掉派生部分。")],
  ["Pimpl 减编译时间", "const 方法默认", "资源类 Rule of Five", "单例用 Meyers"],
  "《Effective C++》Item 4-12")

T("C++", "继承与多态",
  "public 继承表示 is-a；虚函数实现动态绑定；纯虚函数定义接口（抽象类）。",
  "vtable 存函数指针；对象含 vptr；虚调用经 vptr 间接跳转，有缓存友好性成本。",
  "多重继承：多个 vptr；虚继承解决菱形共享基类子对象。",
  "接口用纯虚抽象类；实现 override/final；多态基类 virtual ~T()。",
  "虚函数有 indirection 成本；devirtualization 优化；final 助去虚化。",
  "切片赋值丢失派生信息；dynamic_cast 需 RTTI。",
  "策略模式：多态替换 if-else；工厂返回 unique_ptr<Base>。",
  "override/final 关键字 C++11；编译器检查签名。",
  "typeid/dynamic_cast 调试类型；UBSan 查 undefined downcast。",
  "vs 组合：继承耦合高；Effective C++ 优先 composition。",
  [("虚函数表", "每多态类一 vtable；每对象一 vptr。"), ("override", "显式标记重写；签名必须匹配。"),
   ("抽象类", "含纯虚=0；不可实例化。"), ("虚继承", "shared base 唯一子对象。")],
  [("非 virtual 析构基类", "delete 派生经 Base* 泄漏。"), ("隐藏 overload", "派生同名函数隐藏基类重载。"), ("过深继承树", "难测试。")],
  ["多态基类 virtual dtor", "优先 override", "接口 minimal", "组合替代继承"],
  "C++ FAQ — Virtual Functions")

T("C++", "运算符重载",
  "可重载多数运算符为成员或非成员函数；不可重载 :: .* . ?: sizeof 等。",
  "二元算术常非成员以支持对称性；复合赋值返回 *this；下标[] 通常成员。",
  "operator+ 可能返回 prvalue；RVO/NRVO 消除拷贝。",
  "声明 operator；遵循直觉语义；IO 用友元非成员 << >>。",
  "避免返回 dangling reference；大对象 operator+ 考虑移动。",
  "operator bool 显式防 implicit conversion 到 int。",
  "复数、矩阵库重载 +*；迭代器 operator* operator++。",
  "=default operator= 生成正确移动/拷贝。",
  "单步调试观察 operator 调用链。",
  "vs Python dunder：C++ 更贴近性能，无 GIL。",
  [("成员 vs 非成员", "+= 成员；+ 常非成员。"), ("转换运算符", "explicit 防 silent cast。"),
   ("三路比较 <=>", "C++20 自动生成比较。"), ("空间ship", "默认 <=> 需 =default。")],
  [("operator, 滥用", "难读。"), ("返回 const T", "阻止移动。"), ("不对称 +", "应非成员。")],
  ["非成员 + 对称", "explicit 转换", "C++20 <=>", "IO 友元"],
  "cppreference — Operator overloading")

T("C++", "模板",
  "模板是编译期泛型：函数模板与类模板在实例化时生成特化代码；SFINAE 过滤重载。",
  "两阶段名字查找：模板定义期 + 实例化期；ADL 参与 unqualified 调用。",
  "实例化产生 mangled 符号；显式实例化 extern template 控制编译时间与 ODR。",
  "template<typename T> 定义常放头文件；概念 C++20 constrains 模板参数。",
  "每个 T 实例化一份代码，二进制膨胀；type erasure 减实例化数量。",
  "模板注入：特化顺序影响；避免未定义特化。",
  "std::vector<T>、std::sort 比较器模板；CRTP 静态多态。",
  "concepts requires 子句；-fconcepts-diagnostics-depth。",
  "模板错误信息冗长；static_assert 约束 T。",
  "vs Java 泛型擦除：C++ 单态化零运行时开销。",
  [("实例化", "使用点隐式实例化；显式 template class Foo<int>。"), ("特化", "全特化/偏特化改变实现。"),
   ("SFINAE", "替换失败非错误；enable_if。"), ("概念", "template<typename T> requires Copyable<T>。")],
  [("模板定义放 .cpp", "链接 undefined。"), ("递归模板深度", "编译器 limit。"), ("typename 省略", "依赖名解析错。")],
  ["模板放头文件", "C++20 concepts", "extern template 减编译", "type erasure 减膨胀"],
  "《C++ Templates》Vandevoorde")

T("C++", "STL容器",
  "STL 容器 sequence（vector/deque/list）、associative（set/map）、unordered（hash）与 container adapters。",
  "vector 连续内存 amortized O(1) push_back；map 红黑树 O(log n)；unordered_map 桶+链表均摊 O(1)。",
  "Allocator 控制内存；C++17 PMR 多态资源；迭代器 invalidation 规则因容器而异。",
  "选容器：随机访问→vector；有序键→map；高频查找→unordered_map；中间插入→list。",
  "vector reserve 预分配；emplace_back 原地构造；shrink_to_fit 非强制。",
  "迭代器失效导致 UAF；跨线程需外部锁或 concurrent 容器。",
  "日志缓冲 vector<char>；索引 inverted index unordered_map。",
  "自定义 Allocator C++11；_GLIBCXX_DEBUG 调试模式。",
  "MSan/ASan 查迭代器越界。",
  "vs Java Collection：C++ 值语义，无 GC。",
  [("vector", "capacity/size；扩容 factor 通常 2。"), ("map vs unordered_map", "有序 vs 哈希；hash 需 good hash。"),
   ("迭代器失效", "vector insert 使之后迭代器全失效。"), ("emplace", "转发参数原地构造。")],
  [("vector 中间 insert 频繁", "应 list 或标记删除。"), ("end()-begin() 当索引", "应用 size。"), ("map[] 插入默认", "查用 find。")],
  ["默认 vector", "reserve 已知大小", "emplace 优先", "查 invalidation 表"],
  "cppreference — Containers library")

T("C++", "STL算法",
  "<algorithm> 提供 sort、find、transform、accumulate 等；操作迭代器范围 [first,last)。",
  "sort  introsort O(n log n)；stable_sort 归并；nth_element 部分排序。",
  "算法不拥有容器；需保证迭代器有效；Execution Policy C++17 并行算法。",
  "include 头文件 → 选算法 → 传迭代器 → 必要时自定义 comparator/lambda。",
  "并行 std::execution::par 需无数据竞争；小范围并行反而慢。",
  "未初始化内存用 uninitialized_*；避免对失效迭代器算法。",
  "pipeline transform+filter 用 ranges C++20；top_k nth_element。",
  "#include <execution> 链接 TBB。",
  "观察 comparator 严格弱序；UBSan 查 invalid compare。",
  "vs 手写循环：算法名文档化意图。",
  [("迭代器类别", "随机访问算法需 RandomAccessIterator。"), ("比较器", "strict weak ordering。"),
   ("ranges", "views::filter | views::transform 惰性。"), ("并行算法", "par_unseq 向量化要求。")],
  [("对 list sort", "无 member sort 用 ::sort 需 random access。"), ("比较器非严格弱序", "sort 未定义。"), ("并行修改共享", "数据竞争。")],
  ["优先 std 算法", "ranges 减样板", "并行测基准", "lambda 明确捕获"],
  "cppreference — Algorithms library")

T("C++", "智能指针",
  "unique_ptr 独占所有权；shared_ptr 引用计数；weak_ptr 打破 shared 循环引用。",
  "shared_ptr 控制块存强/弱计数；make_shared 一次分配对象+控制块。",
  "自定义 deleter 类型擦除在 unique_ptr；shared_ptr aliasing constructor。",
  "工厂返回 unique_ptr<Base>；共享用 make_shared；观察循环用 weak_ptr::lock。",
  "atomic ref count 有开销；unique_ptr 零开销等同裸指针。",
  "shared_ptr 非线程安全指向同一对象的并发读写；get() 裸指针不延长生命。",
  "资源管理 FILE* unique_ptr 自定义 deleter fclose。",
  "std::enable_shared_from_this 异步回调延长生命。",
  "跟踪 ref count；weak_ptr expired()。",
  "vs GC：确定性析构；vs Rust Box：运行时计数。",
  [("unique_ptr", "不可拷贝可移动；default deleter delete。"), ("shared_ptr", "拷贝增 strong count。"),
   ("weak_ptr", "不增 strong；lock 得 shared。"), ("make_unique/make_shared", "异常安全与分配优化。")],
  [("shared_ptr 循环引用", "内存泄漏。"), ("从 this 构造 shared", "双控制块。"), ("混用 new[]/delete", "指定 deleter。")],
  ["make_shared 优先", "unique 默认", "weak 破循环", "禁裸 new"],
  "《Effective Modern C++》智能指针章节")

T("C++", "异常处理",
  "try/catch/throw 栈展开调用析构；异常类型按 catch 顺序匹配；noexcept 承诺不抛。",
  "table-driven unwinding：Itanium ABI __cxa_throw/_Unwind_RaiseException。",
  "析构函数默认 noexcept；移动操作应 noexcept 助 vector 强异常保证。",
  "异常仅用于 exceptional；错误码用于 expected 路径；RAII 清理资源。",
  "异常路径零成本直到 throw；热路径 noexcept 避免 unwinding 表。",
  "catch(...) 吞异常泄露信息； noexcept 违反 terminate。",
  "网络库：连接失败 throw 或 expected<T,E> C++23。",
  "-fno-exceptions 嵌入式禁用；Windows /EHsc。",
  "gdb catch throw；std::current_exception 存异常 ptr。",
  "vs 错误码：异常跨层传播；Go 无异常用 error。",
  [("异常保证", "基本/强/无抛。"), ("RAII", "栈展开自动析构。"), ("std::exception", "what() 消息。"), ("expected", "C++23 显式错误值。")],
  [("析构 throw", "terminate。"), ("异常作控制流", "性能差。"), ("catch 值非引用", "切片。")],
  ["RAII 必用", "noexcept 移动", "expected 新代码", "不 catch 空 swallow"],
  "《Exceptional C++》")

T("C++", "RTTI与类型转换",
  "RTTI 提供 typeid、dynamic_cast；需多态类（虚函数）才能 dynamic_cast 引用。",
  "type_info 比较 name()；编译器生成 typeinfo 符号。",
  "static_cast 编译期；reinterpret_cast 低层比特；const_cast 去 const。",
  "层次向下用 dynamic_cast 检失败 nullptr；避免 C 风格 (T*)p。",
  "dynamic_cast 运行时成本；devirtualization 不可用。",
  "reinterpret_cast 可 alias 违规；strict aliasing 仍适用。",
  "插件系统 factory + dynamic_cast；Visitor 替代 RTTI 开关。",
  "-fno-rtti 嵌入式减二进制。",
  "typeid 打印调试；failed dynamic_cast 查继承。",
  "vs Rust Any/downcast：类似运行期类型。",
  [("dynamic_cast", "安全向下；失败指针 null 引用 bad_cast。"), ("static_cast", "相关类型转换。"),
   ("typeid", "运行时类型标识。"), ("禁用 RTTI", "-fno-rtti 无 dynamic_cast。")],
  [("对非多态 dynamic_cast", "编译错或 UB。"), ("C 风格 cast", "四 cast 更安全。"), ("RTTI 滥用", "应用 Visitor。")],
  ["优先 static_cast", "dynamic 检失败", "禁 C cast", "Visitor 替 RTTI"],
  "cppreference — RTTI")

T("C++", "Lambda与函数对象",
  "Lambda [capture](params){ body } 生成闭包类；operator() 可模板化。",
  "捕获 default/copy：[=] [&] [x,&y]；init capture C++14 [ptr=make_unique<T>()]。",
  "闭包大小取决于捕获；无捕获 lambda 可转函数指针。",
  "STL 算法传 lambda；std::function 类型擦除存任意可调用对象。",
  "std::function 可能堆分配；小 lambda 用 auto 或 template 参数。",
  "捕获 dangling reference 若对象已销毁。",
  "回调注册 std::function<void(int)>；线程 pool 任务 lambda。",
  "generic lambda auto 参数 C++14。",
  "gdb 显示 operator() 闭包字段。",
  "vs 函数指针：捕获状态；vs std::bind 已过时。",
  [("捕获列表", "mutable 改值捕获副本。"), ("泛型 lambda", "auto 参数模板 operator()。"),
   ("std::function", "拷贝 Callable；空抛 bad_function_call。"), ("立即调用", "([]{})(); IIFE。")],
  [("[&] 捕获局部引用异步", "UAF。"), ("recursive std::function", "需 wrapper。"), ("过大 function", "SBO 外分配。")],
  ["init capture 移动", "算法用 lambda", "小对象 template", "慎 [=] 异步"],
  "cppreference — Lambda expressions")

T("C++", "并发编程",
  "std::thread、mutex、condition_variable、atomic；C++20 jthread 自动 join。",
  "mutex 非递归默认；lock_guard/unique_lock RAII；死锁用 std::lock 多锁。",
  "memory_order 控制 atomic 可见性；seq_cst 默认最强。",
  "共享数据 mutex 保护；条件变量 wait 防虚假唤醒用谓词；线程池 work queue。",
  "细粒度锁减争用；读多写少 shared_mutex C++17。",
  "数据竞争 UB；TSan 检测。",
  "生产者消费者 queue+condvar；并行 for std::execution::par。",
  "线程数 hardware_concurrency；线程本地 storage thread_local。",
  "TSan/Helgrind；gdb info threads。",
  "vs Java j.u.c：类似抽象；vs Go：共享内存需显式 sync。",
  [("thread", "join/detach；detach 后不可 join。"), ("atomic", "compare_exchange 无锁结构基础。"),
   ("condition_variable", "wait 释放锁；notify_one/all。"), ("jthread", "stop_token 协作取消。")],
  [("detach 后 UAF", "对象已销毁线程仍跑。"), ("忘记 lock", "数据竞争。"), ("condvar 无谓词", "虚假唤醒 bug。")],
  ["RAII 锁", "TSan CI", "最小锁粒度", "jthread 管理生命周期"],
  "《C++ Concurrency in Action》")

T("C++", "C++11/14/17/20新特性",
  "现代 C++ 引入 auto、范围 for、移动语义、constexpr、概念、模块、协程等，改变惯用法。",
  "移动 std::move 转 xvalue；完美转发 std::forward<T>；右值引用 T&&。",
  "模块 C++20 import 减编译；coroutine co_await 状态机变换。",
  "逐步启用标准：-std=c++20；迁移 nullptr、override、constexpr if。",
  "移动避免深拷贝；constexpr 编译期计算减运行时。",
  "coroutine 帧堆分配；模块宏污染减。",
  "ranges + views 管道式数据处理；span 安全数组视图。",
  "modules CMake CXX_MODULE；/std:c++latest MSVC。",
  "概念错误更短；模块依赖 scanner。",
  "vs 旧 C++03：更安全表达力；持续演进 TS。",
  [("移动语义", "五特殊成员自动生成规则变化。"), ("constexpr", "C++20 图灵完备子集。"),
   ("概念", "替代 SFINAE 约束。"), ("协程", "promise_type 定制。")],
  [("std::move 后使用", "moved-from 状态。"), ("auto 过度", "类型不明。"), ("模块混 include", "过渡混乱。")],
  ["目标 C++17 最低", "移动优先", "concepts 新模板", "渐进 modules"],
  "cppreference — C++20")

T("C++", "设计模式",
  "GoF 23 模式在 C++ 中通过虚函数、模板、RAII 实现；Modern C++ 偏 value semantics 与 type erasure。",
  "单例 Meyers static local；工厂 method/abstract factory；Observer 信号槽。",
  "CRTP 静态多态；Policy-based design 模板组合；type erasure 如 std::function。",
  "识别变化点 → 选模式 → 最小实现 → 测试扩展点。",
  "过度模式增加间接层；C++ 可用 compile-time 策略减运行时。",
  "Singleton 全局状态测试难；双重检查锁需 memory_order。",
  "Pimpl 编译防火墙；Strategy std::function 注入。",
  "无特殊配置。",
  "接口 mock 测 Strategy/Observer。",
  "vs Java 模式：C++ 值语义+模板替代部分继承模式。",
  [("RAII", "资源获取即初始化替代部分 Factory。"), ("Strategy", "std::function 运行时替换。"),
   ("Observer", "回调列表；注意 lifetime。"), ("Type erasure", "small buffer optimization。")],
  [("Singleton 滥用", "隐藏依赖。"), ("继承爆炸", "应用组合。"), ("线程不安全单例", "C++11 后 static 安全。")],
  ["组合优于继承", "Pimpl 隐藏", "function 策略", "模式服务需求"],
  "《Design Patterns》GoF + Modern C++ 解读")

T("C++", "性能优化",
  "C++ 零开销抽象：测量后优化；CPU cache、分支预测、内存分配与算法复杂度是主战场。",
  "perf/VTune 采样；PGO 训练热点；LTO 跨单元内联。",
  "false sharing cache line；alignas 避免；NUMA first-touch。",
  "baseline benchmark → profile → 改热点 → 回归测试。",
  "小对象 SSO string；池化 allocator；避免 iostream 热路径。",
  "微优化牺牲可读需注释；volatile 非线程同步。",
  "游戏引擎 ECS 数据导向；HFT 无锁队列。",
  "-march=native -flto；jemalloc。",
  "perf record/report；Cachegrind。",
  "vs 过早优化：Knuth 名言；数据驱动。",
  [("CPU cache", "行大小 64B； locality。"), ("分支预测", "likely 宏；有序数据。"),
   ("RVO/NRVO", "命名返回值优化。"), ("Small Buffer", "string/function 栈上。")],
  [("无 profile 乱优化", "浪费时间。"), ("牺牲 API 换速度", "维护债。"), ("多线程 false sharing", "性能骤降。")],
  ["先测后优", "LTO/PGO 发布", "DOD 布局", "文档化假设"],
  "Agner Fog optimization manuals")

# Continue with remaining domains - script will be extended
