#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Populate remaining 系统底层 module specs (101 modules)."""

import sys
sys.path.insert(0, "/workspace/article_generator/manual")
from _system_module_specs import _add, _concepts, _pitfalls, MODULE_SNIPPETS

def populate():
    # ===== 操作系统原理 (11) =====
    D = "操作系统原理"
    data = {
        "操作系统概述": dict(
            intro="操作系统管理硬件资源并为应用提供抽象：进程、内存、文件与 I/O。批处理、分时、实时与分布式 OS 反映不同设计目标。",
            concepts=_concepts(
                ("OS 四大功能", "处理器管理、存储管理、设备管理、文件管理，向上提供系统调用接口。"),
                ("内核态与用户态", "特权级隔离，trap 进入内核执行敏感操作，保护系统安全。"),
                ("系统调用", "用户程序请求内核服务的唯一受控入口，如 read、fork、mmap。"),
                ("中断与异常", "硬件中断异步事件；异常如页故障、除零同步处理。"),
                ("微内核 vs 宏内核", "微内核仅核心在内核态，L4；宏内核 Linux/Windows 性能路径更短。"),
            ),
            mechanism="应用通过 API→库函数→系统调用→内核子系统→硬件完成请求。",
            internals="Linux 单内核模块化加载驱动；Windows NT 混合内核。",
            workflow="从 man page 与 syscall 表理解接口；用 strace 观察实际调用。",
            performance="系统调用有上下文切换开销，批量 I/O 与 mmap 可减少次数。",
            security="权限位与 capability 限制操作；沙箱依赖内核隔离原语。",
            case_study="容器共享宿主机内核，依赖 namespace 实现进程视图隔离。",
            comparison="单体内核 vs 微内核：前者性能优，后者形式化验证易。",
        ),
        "进程与线程": dict(
            intro="进程拥有独立地址空间与资源；线程共享进程资源是调度单位。PCB 记录状态、寄存器、内存指针与打开文件。",
            concepts=_concepts(
                ("PCB", "进程控制块存 pid、状态、程序计数器、寄存器、内存管理信息。"),
                ("五状态模型", "新建、就绪、运行、阻塞、终止；就绪队列与阻塞队列调度。"),
                ("线程模型", "用户级线程库调度；内核级线程 1:1 映射，Linux NPTL。"),
                ("上下文切换", "保存/恢复寄存器与栈，切换地址空间，有 cache 失效成本。"),
                ("轻量进程", "clone 标志控制共享资源范围，介于进程线程之间。"),
            ),
            mechanism="调度器从就绪队列选进程分配 CPU；阻塞因 I/O 或等待事件让出 CPU。",
            internals="Linux task_struct 统一表示进程与线程；线程组 tgid 与 pid 关系。",
            workflow="分析 ps 输出；理解 fork 后父子并发执行。",
            performance="减少线程切换；I/O 密集用异步避免阻塞线程。",
            security="进程隔离防越界访问；ptrace 调试需授权。",
            case_study="浏览器多进程隔离渲染与网络，单页崩溃不影响全局。",
            comparison="多进程隔离强开销大；多线程共享内存快但需同步。",
        ),
        "进程调度": dict(
            intro="调度算法决定就绪队列中谁获 CPU。FCFS、SJF、优先级、时间片轮转与多级反馈队列是经典策略。",
            concepts=_concepts(
                ("FCFS", "先来先服务，非抢占，护航效应短作业等长作业。"),
                ("SJF", "短作业优先，平均等待时间最优，需预知或估计 burst time。"),
                ("时间片轮转", "抢占式，时间片用完重新入队，响应时间好。"),
                ("优先级调度", "高优先级先运行，可能饥饿需老化提升低优先级。"),
                ("多级反馈队列", "新进程最高级队列，用完时间片降级，综合响应与吞吐。"),
            ),
            mechanism="调度触发：时间片到、I/O 完成、优先级变化；保存现场切换进程。",
            internals="Linux CFS 用 vruntime 红黑树，公平共享 CPU。",
            workflow="计算平均周转时间与等待时间评估算法；模拟调度过程。",
            performance="I/O 密集与 CPU 密集混合负载选 MLFQ；实时用 EDF/RMS。",
            security="调度侧信道（如 cache timing）是安全研究领域。",
            case_study="交互式桌面 OS 用小时间片保证 UI 响应；批处理用大时间片提吞吐。",
            comparison="抢占 vs 非抢占：前者响应好，后者实现简单。",
        ),
        "进程同步": dict(
            intro="临界区访问需互斥。信号量、管程、条件变量与原子操作解决生产者消费者、读者写者问题。",
            concepts=_concepts(
                ("临界区", "访问共享资源的代码段，同一时刻仅一进程进入。"),
                ("信号量", "P/V 操作，计数信号量表资源数，二元信号量作互斥锁。"),
                ("管程", "高级抽象，enter/leave 自动互斥，condition wait/signal。"),
                ("哲学家就餐", "经典死锁示例，限制同时拿筷或有序拿筷解决。"),
                ("硬件支持", "Test-and-Set、CAS 实现原子，支撑用户态锁。"),
            ),
            mechanism="P 操作减计数，为 0 阻塞；V 操作增计数唤醒等待者。",
            internals="Linux futex 用户态快速路径，争用时内核排队。",
            workflow="识别共享变量→定义临界区→选择锁或信号量→验证无竞态。",
            performance="锁粒度影响并行度；读写锁优化读多写少。",
            security="竞态可导致 TOCTOU 与权限绕过。",
            case_study="有界缓冲区用 mutex+cond 实现生产者消费者，避免忙等。",
            comparison="信号量 vs 互斥锁：前者可同步多个资源，后者二元互斥。",
        ),
        "死锁处理": dict(
            intro="死锁四条件：互斥、占有且等待、不可抢占、循环等待。预防、避免、检测恢复与鸵鸟策略是处理手段。",
            concepts=_concepts(
                ("死锁条件", "四条件同时满足才死锁，破坏任一可预防。"),
                ("银行家算法", "避免算法，分配前检测是否仍处安全状态。"),
                ("资源分配图", "有向图检测环路判断死锁可能。"),
                ("检测与恢复", "定期检测，终止进程或剥夺资源。"),
                ("锁顺序", "全局定义锁获取顺序破坏循环等待，工程常用。"),
            ),
            mechanism="银行家算法 Need≤Available 且存在安全序列才分配。",
            internals="数据库两阶段锁与死锁检测；Linux lockdep 开发期检测。",
            workflow="设计时定义锁层次；运行时监控等待图；超时与重试降级。",
            performance="过细锁顺序增加复杂度；检测算法有周期开销。",
            security="死锁可导致 DoS，需 watchdog 与超时。",
            case_study="MySQL InnoDB 死锁检测回滚代价小的事务，应用重试。",
            comparison="预防严格可能降并发；检测恢复适合不确定场景。",
        ),
        "内存管理": dict(
            intro="内存管理分配、回收与保护。分区、分页、分段及段页式结合，解决碎片与共享问题。",
            concepts=_concepts(
                ("分页", "固定大小页框，外部碎片无，内部碎片最后一页浪费。"),
                ("分段", "逻辑单位代码段数据段，利于共享与保护，外部碎片需紧凑。"),
                ("页表", "逻辑页号到物理框号映射，多级页表节省空间。"),
                ("TLB", "页表缓存，命中加速地址翻译，上下文切换需刷新。"),
                ("交换区", "内存不足换出页到磁盘，颠簸 thrashing 需控制。"),
            ),
            mechanism="MMU 硬件查页表，缺页中断由 OS 分配页框或换页。",
            internals="x86 四级页表；ARM 多级类似；大页减少 TLB miss。",
            workflow="计算有效访问时间 EAT=hit*TLB+(1-hit)*内存访问。",
            performance="工作集算法控制并发度防颠簸；局部性优化布局。",
            security="NX 位防代码注入；ASLR 随机化布局。",
            case_study="32 位系统 PAE 扩物理寻址，应用仍 4GB 虚拟空间。",
            comparison="分页 vs 分段：现代 OS 以分页为主，段用于权限。",
        ),
        "虚拟内存": dict(
            intro="虚拟内存给每进程独立地址空间，按需调页。页面置换 LRU、Clock、FIFO 与工作集模型指导策略。",
            concepts=_concepts(
                ("需求调页", "首次访问缺页中断才加载，节省物理内存。"),
                ("页面置换", "无空闲框时选牺牲页，修改位决定写回。"),
                ("LRU", "置换最久未用，近似 Clock 二次_chance 算法。"),
                ("Belady 异常", "FIFO 增加页框数反而缺页率升，LRU 无此问题。"),
                ("工作集", "窗口内访问页集合，用于驻留集管理与颠簸控制。"),
            ),
            mechanism="引用位由硬件置位，OS 定期清零扫描实现近似 LRU。",
            internals="Linux active/inactive LRU 链表；swap 分区或文件。",
            workflow="模拟页面引用串计算缺页次数比较算法。",
            performance="预取与 readahead；mlock 关键页防换出。",
            security="交换分区可能残留敏感数据，加密 swap 或禁用。",
            case_study="数据库 buffer pool 自管缓存，绕过 OS 页面置换更可预测。",
            comparison="全局 vs 局部置换：后者每进程独立框，隔离性好。",
        ),
        "文件系统": dict(
            intro="文件系统组织数据为文件与目录，管理空闲空间、目录结构与元数据。FAT、inode 与日志文件系统各有权衡。",
            concepts=_concepts(
                ("inode", "Unix 文件元数据与块指针，目录项映射名到 inode。"),
                ("FAT", "文件分配表链式块，简单无权限，U 盘常用。"),
                ("日志 FS", "先写日志再提交，崩溃恢复一致，ext4/xfs。"),
                ("目录结构", "单级、两级、树形；查找线性或哈希。"),
                ("空闲空间", "位图、空闲链表、分组管理分配块。"),
            ),
            mechanism="创建文件分配 inode 与数据块；删除释放并更新位图。",
            internals="ext4 extent 连续块；硬链接共享 inode，软链接独立。",
            workflow="mkfs 格式化；mount 挂载；fsck 修复不一致。",
            performance="顺序分配减寻道；日志批量提交提写吞吐。",
            security="权限位 uid/gid；ACL 扩展；只读挂载防篡改。",
            case_study="断电后 ext4 日志回放，元数据一致仅丢最后几秒数据。",
            comparison="日志 vs 非日志：前者恢复快，写放大略高。",
        ),
        "IO系统": dict(
            intro="I/O 软件层次：用户层→设备无关 OS 层→驱动→中断处理。同步异步、阻塞非阻塞与 SPOOLing 是核心概念。",
            concepts=_concepts(
                ("设备分类", "块设备按块随机访问；字符设备字节流；网络特殊。"),
                ("DMA", "直接内存访问减 CPU 拷贝，描述符链式传输。"),
                ("中断驱动 I/O", "设备完成发中断，CPU 处理而非轮询。"),
                ("缓冲与缓存", "单缓冲、双缓冲、缓冲池平滑速度差异。"),
                ("SPOOLing", "假脱机，磁盘队列打印任务，共享独占设备。"),
            ),
            mechanism="read 系统调用→VFS→块层→驱动→DMA→中断完成。",
            internals="Linux bio 提交块 I/O；request queue 与调度器。",
            workflow="区分程序 I/O、线路缓冲与内核缓冲三层。",
            performance="异步 I/O aio/io_uring 重叠计算与 I/O。",
            security="直接 I/O 到设备节点需权限；DMA 攻击需 IOMMU。",
            case_study="打印机 SPOOL 队列，多用户提交不互斥等待硬件。",
            comparison="轮询适合低延迟设备；中断适合慢设备。",
        ),
        "磁盘调度": dict(
            intro="磁盘调度算法减少寻道时间。FCFS、SSTF、SCAN、C-SCAN、LOOK 在吞吐与公平间权衡。",
            concepts=_concepts(
                ("寻道时间", "磁头移动到柱面，主导机械盘延迟。"),
                ("SSTF", "最短寻道优先，可能饥饿远端请求。"),
                ("SCAN 电梯", "磁头单向扫描到端点反向，公平性较好。"),
                ("C-SCAN", "只单向服务，返回快速扫不处理，均匀等待。"),
                ("LOOK", "SCAN 改进，不到物理端点只到最后请求。"),
            ),
            mechanism="I/O 调度器合并相邻请求，elevator 算法排序。",
            internals="Linux mq-deadline、kyber、bfq；SSD 用 noop/none。",
            workflow="给定请求柱面序列计算各算法总寻道距离。",
            performance="SSD 无寻道，重随机 IOPS 与队列深度；NVMe 多队列。",
            security="磁盘加密与安全擦除独立于调度。",
            case_study="数据库随机读多，SSD 换机械盘后调度算法影响变小。",
            comparison="机械盘 SCAN 有效；SSD 关注 wear 与 FTL。",
        ),
        "安全与保护": dict(
            intro="保护机制控制进程对资源访问。访问矩阵、能力表、ACL 与域是经典模型；现代 OS 结合 LSM 与 capability。",
            concepts=_concepts(
                ("访问矩阵", "主体×客体权限表，稀疏实现为能力或 ACL。"),
                ("ACL", "每对象列允许的主体与权限，文件系统常用。"),
                ("能力表", "每进程持能力列表，Amoeba 等微内核用。"),
                ("特权级", "环 0 内核环 3 用户，syscall 切换。"),
                ("LSM", "Linux 安全模块钩子 SELinux/AppArmor 强制策略。"),
            ),
            mechanism="每次访问查 ACL 或 capability；拒绝则 EACCES。",
            internals="SELinux 类型强制 TE 规则；seccomp 系统调用过滤。",
            workflow="最小权限设计；定期审计权限与 setuid 文件。",
            performance="LSM 钩子有微小开销，可忽略相对 I/O。",
            security="纵深防御：认证、授权、审计、加密分层。",
            case_study="容器 seccomp+AppArmor 限制逃逸面，默认丢弃危险 syscall。",
            comparison="DAC 传统 Unix 权限 vs MAC SELinux 强制策略。",
        ),
    }
    for m, kw in data.items():
        _add(D, m, **kw)

    # ===== 计算机网络 (10) =====
    D = "计算机网络"
    data = {
        "网络体系结构": dict(
            intro="OSI 七层与 TCP/IP 四层是网络分层参考模型。封装与解封装使各层独立演进，上层无需关心物理传输细节。",
            concepts=_concepts(
                ("OSI 七层", "物理、数据链路、网络、传输、会话、表示、应用，理论完整。"),
                ("TCP/IP 四层", "网络接口、网际、传输、应用，互联网事实标准。"),
                ("PDU", "每层协议数据单元：帧、包、段、报文。"),
                ("封装", "上层 PDU 加首部作为下层载荷，逐层向下传递。"),
                ("服务原语", "请求、指示、响应、确认描述层间交互。"),
            ),
            mechanism="发送端自上而下加首部；接收端自下而上剥首部递交上层。",
            internals="Linux sk_buff 贯穿协议栈各层指针移动。",
            workflow="Wireshark 按层展开分析；理解哪层处理哪类问题。",
            performance="分层有头部开销；协议卸载 TSO/GSO 减 CPU。",
            security="各层有对应威胁：物理窃听、ARP 欺骗、IP 欺骗、TCP 劫持等。",
            case_study="HTTPS 在应用层加密，下层仍可见 IP 端口但内容保密。",
            comparison="OSI 教学清晰；TCP/IP 工程实用。",
        ),
        "物理层与数据链路层": dict(
            intro="物理层传输比特流；数据链路层组帧、差错检测与 MAC 寻址。以太网与 Wi-Fi 是局域网主流技术。",
            concepts=_concepts(
                ("以太网帧", "前导码、目的/源 MAC、类型、载荷、FCS CRC 校验。"),
                ("MAC 地址", "48 位硬件地址，单播/广播/多播最低位标志。"),
                ("CSMA/CD", "经典以太网载波侦听冲突检测，全双工交换机下弱化。"),
                ("VLAN", "802.1Q 标签扩展 LAN，逻辑隔离广播域。"),
                ("ARP", "IPv4 地址解析 MAC，同网段广播查询。"),
            ),
            mechanism="NIC 收帧 DMA 到内存，驱动递交内核；发送组帧经队列发出。",
            internals="MTU 1500 限制 IP 分片；巨型帧 jumbo 9000 减开销需端到端支持。",
            workflow="ip link 查接口；tcpdump ether 过滤；arp -a 看缓存。",
            performance="全双工交换机消除冲突；链路聚合 bonding 提带宽。",
            security="MAC 伪造；端口安全 802.1X；DHCP 欺骗防护。",
            case_study="跨交换机 VLAN 不通，查 trunk 是否允许该 VLAN tag。",
            comparison="以太网 vs Wi-Fi：前者稳定有线；后者共享介质 CSMA/CA。",
        ),
        "网络层IP": dict(
            intro="IP 提供无连接尽最大努力交付。IPv4 32 位地址与 IPv6 128 位；路由表最长前缀匹配转发。",
            concepts=_concepts(
                ("IPv4 首部", "版本、TTL、协议号、源目的地址、可选分片字段。"),
                ("CIDR", "无类域间路由，前缀长度表网络规模，如 /24。"),
                ("NAT", "私有地址经路由器地址转换访问公网，破坏端到端。"),
                ("ICMP", "差错与诊断，ping 用 Echo Request/Reply，TTL 超时 traceroute。"),
                ("IPv6", "更大地址空间、无广播用多播、简化首部、内置 IPsec。"),
            ),
            mechanism="路由器查 FIB 下一跳；TTL 每跳减 1 防环；分片在路径 MTU 不足时发生。",
            internals="Linux 转发 net.ipv4.ip_forward；策略路由 rule+table。",
            workflow="ip route 查表；ping/traceroute 测连通；tcpdump host 过滤。",
            performance="ECMP 等价多路径负载分担；连接跟踪影响 NAT 性能。",
            security="源路由攻击禁用；反欺骗 uRPF；防火墙 stateful 过滤。",
            case_study="双 ISP 用策略路由，国内流量走电信国际走联通。",
            comparison="IPv4+NAT vs IPv6 端到端：后者简化 NAT 但迁移成本高。",
        ),
        "传输层TCP/UDP": dict(
            intro="TCP 面向连接可靠字节流，三次握手、滑动窗口与拥塞控制；UDP 无连接报文，低延迟可丢包。",
            concepts=_concepts(
                ("TCP 握手", "SYN→SYN-ACK→ACK 同步序列号，防旧连接混淆。"),
                ("滑动窗口", "流量控制，接收方 rwnd 限制发送方在途数据。"),
                ("拥塞控制", "cwnd 慢启动、拥塞避免、快重传快恢复。"),
                ("TIME_WAIT", "主动关闭方等待 2MSL 防迟到的段干扰新连接。"),
                ("UDP", "无连接无重传，DNS、QUIC、游戏状态常用。"),
            ),
            mechanism="TCP 序号确认重传；RTO 超时指数退避；SACK 选择性确认。",
            internals="Linux cubic/bbr 拥塞控制插件；syncookies 半连接保护。",
            workflow="ss -tin 看 cwnd/rtt；nc -u 测 UDP；理解四次挥手。",
            performance="窗口缩放选项大 BDP 网络；TCP_NODELAY 禁 Nagle。",
            security="SYN flood；TCP 重置攻击；加密用 TLS  atop TCP。",
            case_study="移动网络高丢包，BBR 比 cubic 视频卡顿少。",
            comparison="TCP 可靠 vs UDP 实时：QUIC 在 UDP 上实现可靠多路复用。",
        ),
        "应用层协议": dict(
            intro="应用层协议定义进程间通信语义。HTTP、DNS、SMTP、FTP 等基于 TCP/UDP，REST 与 gRPC 是现代 API 形态。",
            concepts=_concepts(
                ("HTTP/1.1", "请求响应无状态，Keep-Alive 复用连接，Host 头虚拟主机。"),
                ("HTTP/2", "二进制分帧、多路复用、头部压缩 HPACK。"),
                ("DNS", "层次分布式，递归与迭代查询，A/AAAA/CNAME 记录。"),
                ("TLS", "握手协商密码套件，证书链验证服务器身份。"),
                ("gRPC", "HTTP/2 + Protobuf，强类型 RPC，流式支持。"),
            ),
            mechanism="客户端解析 URL→DNS 解析→TCP 连接→TLS 握手→HTTP 请求响应。",
            internals="CDN 边缘缓存静态；SNI 同 IP 多证书。",
            workflow="curl -v 看全过程；dig 查 DNS；openssl s_client 测 TLS。",
            performance="HTTP/2 减队头阻塞；缓存 Cache-Control；连接池。",
            security="HSTS 强制 HTTPS；DNSSEC 防劫持；证书固定。",
            case_study="API 从 REST JSON 迁 gRPC，序列化与连接复用延迟降 30%。",
            comparison="REST 通用缓存友好；gRPC 高性能内部服务。",
        ),
        "网络安全": dict(
            intro="网络安全涵盖机密性、完整性、可用性与认证。防火墙、VPN、IDS/IPS 与 TLS 构成防御体系。",
            concepts=_concepts(
                ("防火墙", "包过滤与状态检测，默认拒绝白名单开放端口。"),
                ("VPN", "IPsec 或 SSL VPN 隧道加密远程接入内网。"),
                ("IDS/IPS", "签名与异常检测，IPS 内联阻断。"),
                ("DDoS", "流量清洗与 Anycast 分散，SYN proxy 防护。"),
                ("零信任", "永不信任始终验证，微隔离替代边界安全。"),
            ),
            mechanism="TLS 记录层加密应用数据；IPsec AH/ESP 网络层保护。",
            internals="nftables 替代 iptables；WireGuard 现代 VPN 协议。",
            workflow="nmap 授权扫描；openssl 验证证书；规则变更前备份。",
            performance="TLS 会话复用与硬件加速；防火墙状态表容量规划。",
            security="最小开放端口；定期补丁；分层防御。",
            case_study="办公网 Zero Trust，每应用 mTLS 无传统边界 VPN。",
            comparison="IPsec vs SSL VPN：前者 L3 全网；后者应用层易部署。",
        ),
        "网络编程": dict(
            intro="Socket API 实现网络程序。阻塞、非阻塞、多路复用与线程池是构建高并发服务的关键技术。",
            concepts=_concepts(
                ("服务端模型", "迭代、每连接一线程、线程池、Reactor、Proactor。"),
                ("非阻塞 I/O", "EAGAIN 表示暂不可读写，需 epoll 等待就绪。"),
                ("地址解析", "getaddrinfo 支持 IPv4/IPv6 与 service 名。"),
                ("半关闭", "shutdown SHUT_WR 发 FIN 仍可读对端数据。"),
                ("粘包", "TCP 字节流需长度前缀或分隔符定界消息。"),
            ),
            mechanism="bind→listen→accept 循环；或 connect 客户端；send/recv 处理数据。",
            internals="SO_REUSEPORT 多进程监听负载均衡。",
            workflow="先写 echo 服务；再加协议解析；最后 epoll 优化。",
            performance="连接池复用；批量 writev；减少小包。",
            security="输入校验防注入；TLS 包装；限连接速率。",
            case_study="Redis 单线程 epoll 事件驱动，十万 QPS 级别。",
            comparison="Reactor 同步 I/O vs Proactor 异步完成端口。",
        ),
        "网络性能": dict(
            intro="网络性能由带宽、延迟、吞吐与 PPS 决定。BDP 指导窗口大小；拥塞控制与缓冲区膨胀影响实际体验。",
            concepts=_concepts(
                ("BDP", "带宽延迟积，管道在途数据量，指导 TCP 窗口。"),
                ("RTT", "往返时延，物理距离与排队主导。"),
                ("吞吐", "单位时间比特数，受窗口与丢包率限制。"),
                ("PPS", "每秒包数，小包场景 CPU 成为瓶颈。"),
                ("缓冲区膨胀", "过大缓冲增延迟，CoDel/fq 缓解。"),
            ),
            mechanism="iperf3 测带宽；ping 测 RTT；ss 看重传率。",
            internals="TCP pacing 平滑发送；BBR 估计瓶颈带宽。",
            workflow="基线测试→定位瓶颈层→调内核与应用→复测对比。",
            performance="增大窗口与队列需平衡延迟；XDP 旁路内核栈。",
            security="性能测试勿对未授权目标压测。",
            case_study="跨洋链路 BDP 大，调大 net.core.rmem 与窗口缩放后吞吐翻倍。",
            comparison="吞吐优化 vs 延迟优化：CDN 边缘减 RTT；大窗口提吞吐。",
        ),
        "无线网络": dict(
            intro="无线链路共享介质、易误码与隐藏终端问题。802.11 Wi-Fi 与蜂窝 4G/5G 是主流无线接入技术。",
            concepts=_concepts(
                ("802.11 帧", "管理、控制、数据帧；SSID BSSID 标识网络。"),
                ("CSMA/CA", "无线冲突避免，RTS/CTS 可选减隐藏终端。"),
                ("漫游", "AP 间切换，802.11r 快速过渡。"),
                ("WPA3", "SAE 替代 PSK，抵御离线字典攻击。"),
                ("5G 架构", "gNB 核心网分离，网络切片与边缘计算。"),
            ),
            mechanism="关联认证→四次握手派生 PTK→加密数据帧。",
            internals="MIMO 多天线提速率；波束成形定向信号。",
            workflow="iwconfig/iw 查链路；频谱分析查干扰；规划信道不重叠。",
            performance="5GHz 信道多干扰少；Wi-Fi 6 OFDMA 多用户。",
            security="企业 802.1X；访客隔离 VLAN；WPS 应禁用。",
            case_study="办公室 2.4GHz 拥挤，迁 5GHz 并固定信道后吞吐稳定。",
            comparison="Wi-Fi 便捷 vs 有线稳定；5G 移动广覆盖高资费。",
        ),
        "网络管理": dict(
            intro="网络管理含配置、监控、故障与安全管理。SNMP、NetFlow 与自动化 IaC 支撑大规模运维。",
            concepts=_concepts(
                ("SNMP", "MIB 对象 OID 查询，v3 加密认证。"),
                ("NetFlow/sFlow", "流量采样分析源目与协议分布。"),
                ("配置管理", "Ansible 批量推送路由器交换机配置。"),
                ("SLA", "可用性与延迟指标，驱动容量规划。"),
                ("变更管理", "变更窗口、回滚与审计日志。"),
            ),
            mechanism="采集器轮询 SNMP→时序库存储→Grafana 可视化告警。",
            internals="YANG 模型 NETCONF 结构化配置网络设备。",
            workflow="发现资产→基线配置→监控告警→故障 runbook。",
            performance="采样率与存储成本平衡；流分析识别大流量。",
            security="SNMP community 弱口令风险；管理网隔离。",
            case_study="核心交换机 CPU 高，NetFlow 发现某主机 ARP 扫描触发。",
            comparison="SNMP 简单广泛 vs gNMI 流式现代可编程网络。",
        ),
    }
    for m, kw in data.items():
        _add(D, m, **kw)

    return len(MODULE_SNIPPETS)

if __name__ == "__main__":
    n = populate()
    print(f"After part1 rest: {n}")
